import { PERMISSIONS, SUPER_ADMIN_ROLE_CODE } from './permissions.catalog';
import { RoleStatus } from './schemas/role.schema';

export type RoleSeedDefinition = {
  code: string;
  name: string;
  description: string;
  permissions: string[];
  bypassPermissions?: boolean;
  isSystem: true;
  status: RoleStatus.Active;
};

const ALL = [...PERMISSIONS];

const VIEW_REPORTS = ['report.view', 'report.export', 'dashboard.view', 'audit.view'] as const;

const NOTIFICATION_USER = ['notification.view'] as const;
const NOTIFICATION_MANAGE = [
  'notification.view',
  'notification.send',
  'notification.manage',
] as const;

const DIRECTOR_DIGEST = [
  'director_digest.view',
  'director_digest.send',
] as const;

const PROJECT_VIEW = [
  'project.view',
  'boq.view',
  'dpr.view',
  'measurement.view',
  'material_consumption.view',
  'contractor.view',
  'contractor_agreement.view',
  'labour_category.view',
  'manpower_plan.view',
  'manpower_shortfall.view',
  'document.view',
  'dashboard.view',
  ...NOTIFICATION_USER,
] as const;

const INVESTOR_MANAGE = [
  'investor.view',
  'investor.view_all',
  'investor.create',
  'investor.update',
  'investor.verify_kyc',
  'investor.activate',
  'investor.upload_document',
] as const;

const PARTICIPANT_MANAGE = [
  'project_participant.view',
  'project_participant.create',
  'project_participant.update',
  'project_participant.submit',
  'project_participant.approve',
  'project_participant.finalize',
  'project_participant.upload_document',
] as const;

const COMMITMENT_MANAGE = [
  'contribution_commitment.view',
  'contribution_commitment.create',
  'contribution_commitment.submit',
  'contribution_commitment.approve',
  'contribution_commitment.amend',
  'contribution_commitment.cancel',
  'contribution_commitment.record_receipt',
] as const;

const RECEIPT_MANAGE = [
  'contribution_receipt.view',
  'contribution_receipt.create',
  'contribution_receipt.submit',
  'contribution_receipt.verify',
  'contribution_receipt.post',
  'contribution_receipt.cancel',
  'contribution_receipt.upload_document',
] as const;

const FINANCE_CORE = [
  'account.view',
  'account.manage',
  'journal.view',
  'journal.create',
  'journal.post',
  'journal.reverse',
  'bank.view',
  'bank.manage',
  'bank.view_sensitive',
  'bank_reconciliation.view',
  'bank_reconciliation.manage',
  'bank_reconciliation.import',
  'bank_reconciliation.match',
  'bank_reconciliation.post',
  'cash.view',
  'cash.manage',
  'expense_category.view',
  'expense_category.manage',
  'expense.view',
  'expense.create',
  'expense.approve',
  'expense.post',
  'petty_cash.view',
  'petty_cash.request',
  'petty_cash.approve',
  'petty_cash.fund',
  'payment.view',
  'payment.release',
  'payment.approve',
  'vendor_invoice.view',
  'vendor_invoice.approve',
  'vendor_invoice.post',
  ...INVESTOR_MANAGE,
  ...PARTICIPANT_MANAGE,
  ...COMMITMENT_MANAGE,
  ...RECEIPT_MANAGE,
  'investment.view',
  'investment.create',
  'investment.approve',
  'investor_portal.view',
  'investor_portal.manage',
  'financial_year.view',
  'financial_year.manage',
  'financial_year.unlock',
  'period_closure.view',
  'period_closure.manage',
  'period_closure.reopen',
  'period_closure.approve_reopen',
  'company.view',
  ...NOTIFICATION_MANAGE,
  ...DIRECTOR_DIGEST,
  ...VIEW_REPORTS,
] as const;

/**
 * Initial system roles. Access is granted only via these permission lists
 * (except Super Admin bypass). Director titles are not special-cased in code.
 */
export const ROLE_SEEDS: RoleSeedDefinition[] = [
  {
    code: SUPER_ADMIN_ROLE_CODE,
    name: 'Super Admin',
    description: 'Full system access; bypasses permission checks',
    permissions: ALL,
    bypassPermissions: true,
    isSystem: true,
    status: RoleStatus.Active,
  },
  {
    code: 'MANAGING_DIRECTOR',
    name: 'Managing Director',
    description: 'Executive oversight across projects, finance, and approvals',
    permissions: [
      'company.view',
      'company.update',
      'company.upload_logo',
      'financial_year.view',
      'financial_year.manage',
      'financial_year.unlock',
      'period_closure.view',
      'period_closure.manage',
      'period_closure.reopen',
      'period_closure.approve_reopen',
      'user.view',
      'user.create',
      'user.update',
      'user.assign_role',
      'user.assign_project',
      'session.revoke',
      'employee.view',
      'employee.create',
      'employee.update',
      'employee.deactivate',
      'department.view',
      'department.manage',
      'designation.view',
      'designation.manage',
      'permission.override.manage',
      'site.view',
      'site.manage',
      'site_access.view',
      'site_access.assign',
      'site_access.manage',
      'project.view',
      'project.create',
      'project.update',
      'project.close',
      'project.upload_document',
      'project_access.view',
      'project_access.assign',
      'project_access.manage',
      'project_access.audit_view',
      'director.view',
      'director.create',
      'director.update',
      'director.upload_document',
      'shareholding.view',
      'shareholding.propose',
      'shareholding.approve',
      'document.view',
      'document.upload',
      'document.download',
      'document.replace',
      'document.archive',
      'approval.view',
      'approval.act',
      'approval.configure',
      'approval.cancel',
      ...INVESTOR_MANAGE,
      ...PARTICIPANT_MANAGE,
      ...COMMITMENT_MANAGE,
      ...RECEIPT_MANAGE,
      'investment.view',
      'investment.approve',
      'investor_portal.view',
      'investor_portal.manage',
      'expense.view',
      'expense.approve',
      'payment.view',
      'payment.approve',
      'purchase.view',
      'purchase.approve',
      'stock.view',
      'stock.count.director_approve',
      'booking.view',
      'booking.approve',
      'approval.view',
      'approval.act',
      'document.view',
      ...NOTIFICATION_MANAGE,
      ...DIRECTOR_DIGEST,
      ...VIEW_REPORTS,
    ],
    isSystem: true,
    status: RoleStatus.Active,
  },
  {
    code: 'DIRECTOR',
    name: 'Director',
    description:
      'Board-level view and selective approvals; all-project access only via project assignment config',
    permissions: [
      'company.view',
      'financial_year.view',
      'user.view',
      'employee.view',
      'department.view',
      'designation.view',
      'site.view',
      'site_access.view',
      'project.view',
      'project_access.view',
      'director.view',
      'shareholding.view',
      'investor.view',
      'investor.view_all',
      'project_participant.view',
      'contribution_commitment.view',
      'contribution_receipt.view',
      'investment.view',
      'investor_portal.view',
      'investor_portal.manage',
      'expense.view',
      'payment.view',
      'purchase.view',
      'stock.view',
      'stock.count.director_approve',
      'booking.view',
      'approval.view',
      'approval.act',
      'document.view',
      'running_bill.view',
      'running_bill.approve',
      ...NOTIFICATION_MANAGE,
      ...DIRECTOR_DIGEST,
      ...VIEW_REPORTS,
    ],
    isSystem: true,
    status: RoleStatus.Active,
  },
  {
    code: 'FINANCE_DIRECTOR',
    name: 'Finance Director',
    description: 'Owns finance policy, releases, and accounting oversight',
    permissions: [
      ...FINANCE_CORE,
      'user.view',
      'project.view',
      'vendor.view',
      'customer.view',
      'director.view',
      'shareholding.view',
      'shareholding.propose',
      'shareholding.approve',
      'stock.view',
      'stock.count.director_approve',
      'contractor_agreement.view',
      'contractor_agreement.approve',
      'running_bill.view',
      'running_bill.finance_verify',
      'running_bill.approve',
      'running_bill.post',
      'running_bill.pay',
    ],
    isSystem: true,
    status: RoleStatus.Active,
  },
  {
    code: 'FINANCE_MANAGER',
    name: 'Finance Manager',
    description: 'Day-to-day finance operations and approvals',
    permissions: [
      'account.view',
      'journal.view',
      'journal.create',
      'journal.post',
      'bank.view',
      'cash.view',
      'expense.view',
      'expense.create',
      'expense.approve',
      'expense.post',
      'petty_cash.view',
      'petty_cash.approve',
      'petty_cash.fund',
      'payment.view',
      'payment.release',
      'payment.approve',
      'vendor_invoice.view',
      'vendor_invoice.approve',
      'vendor_invoice.post',
      'running_bill.view',
      'running_bill.finance_verify',
      'running_bill.post',
      'running_bill.pay',
      ...INVESTOR_MANAGE,
      ...PARTICIPANT_MANAGE,
      ...COMMITMENT_MANAGE,
      ...RECEIPT_MANAGE,
      'investment.view',
      'investor_portal.view',
      'investor_portal.manage',
      'financial_year.view',
      'company.view',
      'project.view',
      'vendor.view',
      'contractor_agreement.view',
      'contractor_agreement.approve',
      ...VIEW_REPORTS,
    ],
    isSystem: true,
    status: RoleStatus.Active,
  },
  {
    code: 'ACCOUNTANT',
    name: 'Accountant',
    description: 'Journals, expenses, and ledger posting',
    permissions: [
      'account.view',
      'journal.view',
      'journal.create',
      'journal.post',
      'bank.view',
      'cash.view',
      'expense.view',
      'expense.create',
      'expense.post',
      'vendor_invoice.view',
      'vendor_invoice.post',
      'petty_cash.view',
      'petty_cash.request',
      'payment.view',
      'financial_year.view',
      'project.view',
      'vendor.view',
      'report.view',
      'dashboard.view',
    ],
    isSystem: true,
    status: RoleStatus.Active,
  },
  {
    code: 'PROJECT_MANAGER',
    name: 'Project Manager',
    description: 'Project delivery, BOQ, progress, and site coordination',
    permissions: [
      ...PROJECT_VIEW,
      'project.create',
      'project.update',
      'project.upload_document',
      'boq.manage',
      'boq.approve',
      'dpr.create',
      'dpr.review',
      'measurement.create',
      'measurement.certify',
      'material_consumption.manage',
      'material_consumption.approve',
      'contractor.view',
      'contractor.manage',
      'contractor_agreement.view',
      'contractor_agreement.manage',
      'contractor_agreement.approve',
      'labour_category.view',
      'labour_category.manage',
      'attendance.view',
      'attendance.create',
      'attendance.confirm',
      'manpower_plan.view',
      'manpower_plan.manage',
      'manpower_shortfall.view',
      'manpower_shortfall.acknowledge',
      'running_bill.view',
      'running_bill.create',
      'running_bill.verify',
      'running_bill.certify',
      'purchase.view',
      'purchase.request',
      'purchase.approve',
      'stock.view',
      'expense.view',
      'expense.create',
      'document.upload',
      'approval.view',
      'user.view',
      'report.view',
    ],
    isSystem: true,
    status: RoleStatus.Active,
  },
  {
    code: 'PURCHASE_MANAGER',
    name: 'Purchase Manager',
    description: 'Procurement approvals and vendor oversight',
    permissions: [
      'vendor.view',
      'vendor.manage',
      'material.view',
      'material.manage',
      'material_consumption.view',
      'material_consumption.manage',
      'material_consumption.approve',
      'purchase.view',
      'purchase.request',
      'purchase.approve',
      'purchase.order',
      'procurement_master.view',
      'procurement_master.manage',
      'quotation.view',
      'quotation.manage',
      'quotation.finalize',
      'quotation.compare',
      'quotation.recommend',
      'grn.create',
      'grn.approve',
      'quality.view',
      'quality.inspect',
      'vendor_invoice.view',
      'vendor_invoice.create',
      'vendor_invoice.verify',
      'vendor_invoice.match',
      'vendor_invoice.approve',
      'stock.view',
      'payment.view',
      'project.view',
      'document.view',
      'document.upload',
      'approval.view',
      'approval.act',
      'report.view',
      'dashboard.view',
    ],
    isSystem: true,
    status: RoleStatus.Active,
  },
  {
    code: 'PURCHASE_EXECUTIVE',
    name: 'Purchase Executive',
    description: 'Raises PRs/POs and records GRNs',
    permissions: [
      'vendor.view',
      'material.view',
      'purchase.view',
      'purchase.request',
      'purchase.order',
      'procurement_master.view',
      'procurement_master.manage',
      'quotation.view',
      'quotation.manage',
      'quotation.compare',
      'quotation.recommend',
      'grn.create',
      'vendor_invoice.view',
      'vendor_invoice.create',
      'quality.view',
      'stock.view',
      'project.view',
      'document.view',
      'document.upload',
      'dashboard.view',
    ],
    isSystem: true,
    status: RoleStatus.Active,
  },
  {
    code: 'SITE_ENGINEER',
    name: 'Site Engineer',
    description: 'Site execution, DPR, and measurements',
    permissions: [
      ...PROJECT_VIEW,
      'site_access.view',
      'dpr.create',
      'measurement.view',
      'measurement.create',
      'attendance.view',
      'attendance.create',
      'manpower_plan.view',
      'manpower_plan.manage',
      'manpower_shortfall.view',
      'running_bill.view',
      'running_bill.create',
      'running_bill.verify',
      'stock.view',
      'stock.issue',
      'stock.barcode',
      'stock.reserve',
      'material.view',
      'purchase.view',
      'purchase.request',
      'contractor.view',
      'document.upload',
      'expense.view',
      'expense.create',
      'petty_cash.view',
      'petty_cash.request',
    ],
    isSystem: true,
    status: RoleStatus.Active,
  },
  {
    code: 'SITE_SUPERVISOR',
    name: 'Site Supervisor',
    description: 'Site supervision, attendance, and material issues',
    permissions: [
      'project.view',
      'dpr.view',
      'dpr.create',
      'attendance.view',
      'attendance.create',
      'attendance.confirm',
      'manpower_plan.view',
      'manpower_shortfall.view',
      'manpower_shortfall.acknowledge',
      'stock.view',
      'stock.issue',
      'contractor.view',
      'document.view',
      'document.upload',
      'dashboard.view',
    ],
    isSystem: true,
    status: RoleStatus.Active,
  },
  {
    code: 'STOREKEEPER',
    name: 'Storekeeper',
    description: 'Stock receipts, issues, and adjustments',
    permissions: [
      'material.view',
      'material.manage',
      'stock.view',
      'stock.adjust',
      'stock.issue',
      'stock.transfer',
      'stock.reserve',
      'stock.barcode',
      'site.view',
      'site.manage',
      'grn.create',
      'grn.approve',
      'quality.view',
      'quality.inspect',
      'purchase.view',
      'purchase.request',
      'project.view',
      'document.view',
      'document.upload',
      'dashboard.view',
    ],
    isSystem: true,
    status: RoleStatus.Active,
  },
  {
    code: 'SALES_MANAGER',
    name: 'Sales Manager',
    description: 'Units, customers, bookings, and collections',
    permissions: [
      'unit.view',
      'unit.manage',
      'customer.view',
      'customer.manage',
      'booking.view',
      'booking.create',
      'booking.approve',
      'booking.cancel',
      'collection.view',
      'collection.create',
      'collection.approve',
      'collection.refund',
      'project.view',
      'document.view',
      'document.upload',
      'approval.view',
      'approval.act',
      ...VIEW_REPORTS,
    ],
    isSystem: true,
    status: RoleStatus.Active,
  },
  {
    code: 'VENDOR',
    name: 'Vendor',
    description:
      'Vendor portal: invited RFQs, quotation response, and PO acceptance only (no internal staff modules)',
    permissions: [
      'vendor_portal.view',
      'vendor_portal.respond',
      ...NOTIFICATION_USER,
    ],
    isSystem: true,
    status: RoleStatus.Active,
  },
  {
    code: 'INVESTOR',
    name: 'Investor',
    description:
      'Restricted portal: own investor profile and authorised project investments only (no company finance, vendors, customers, or other investors)',
    permissions: [
      'investor.view',
      'investor_portal.view',
      ...NOTIFICATION_USER,
    ],
    isSystem: true,
    status: RoleStatus.Active,
  },
  {
    code: 'AUDITOR',
    name: 'Auditor',
    description: 'Read-only audit of finance and operations',
    permissions: [
      'company.view',
      'financial_year.view',
      'account.view',
      'journal.view',
      'bank.view',
      'cash.view',
      'expense_category.view',
      'expense.view',
      'payment.view',
      'purchase.view',
      'stock.view',
      'project.view',
      'investor.view',
      'investor.view_all',
      'project_participant.view',
      'contribution_commitment.view',
      'contribution_receipt.view',
      'investment.view',
      'booking.view',
      'collection.view',
      'document.view',
      'audit.view',
      'project_access.audit_view',
      'report.view',
      'report.export',
      'dashboard.view',
    ],
    isSystem: true,
    status: RoleStatus.Active,
  },
  {
    code: 'READ_ONLY',
    name: 'Read Only',
    description: 'Broad view access without mutate permissions',
    permissions: [
      'company.view',
      'financial_year.view',
      'user.view',
      'project.view',
      'investor.view',
      'investor.view_all',
      'project_participant.view',
      'contribution_commitment.view',
      'contribution_receipt.view',
      'investment.view',
      'account.view',
      'journal.view',
      'bank.view',
      'cash.view',
      'expense_category.view',
      'expense.view',
      'petty_cash.view',
      'vendor.view',
      'material.view',
      'purchase.view',
      'stock.view',
      'payment.view',
      'boq.view',
      'dpr.view',
      'measurement.view',
      'contractor.view',
      'attendance.view',
      'running_bill.view',
      'unit.view',
      'customer.view',
      'booking.view',
      'collection.view',
      'document.view',
      'approval.view',
      'report.view',
      'dashboard.view',
    ],
    isSystem: true,
    status: RoleStatus.Active,
  },
];
