export enum NumberEntityType {
  COMPANY = 'COMPANY',
  USER = 'USER',
  EMPLOYEE = 'EMPLOYEE',
  ROLE = 'ROLE',
  PROJECT = 'PROJECT',
  DIRECTOR = 'DIRECTOR',
  INVESTOR = 'INVESTOR',
  VENDOR = 'VENDOR',
  CONTRACTOR = 'CONTRACTOR',
  CUSTOMER = 'CUSTOMER',
  BOOKING = 'BOOKING',
  BOOKING_CANCELLATION = 'BOOKING_CANCELLATION',
  MATERIAL = 'MATERIAL',
  PURCHASE_REQUEST = 'PURCHASE_REQUEST',
  RFQ = 'RFQ',
  VENDOR_QUOTATION = 'VENDOR_QUOTATION',
  QUOTATION_COMPARISON = 'QUOTATION_COMPARISON',
  PURCHASE_ORDER = 'PURCHASE_ORDER',
  GOODS_RECEIPT = 'GOODS_RECEIPT',
  QUALITY_INSPECTION = 'QUALITY_INSPECTION',
  STOCK_LEDGER = 'STOCK_LEDGER',
  STOCK_COUNT = 'STOCK_COUNT',
  MATERIAL_ISSUE = 'MATERIAL_ISSUE',
  MATERIAL_RETURN = 'MATERIAL_RETURN',
  VENDOR_INVOICE = 'VENDOR_INVOICE',
  VENDOR_PAYMENT = 'VENDOR_PAYMENT',
  BOQ = 'BOQ',
  DAILY_PROGRESS_REPORT = 'DAILY_PROGRESS_REPORT',
  WORK_MEASUREMENT = 'WORK_MEASUREMENT',
  MATERIAL_CONSUMPTION_STANDARD = 'MATERIAL_CONSUMPTION_STANDARD',
  MATERIAL_CONSUMPTION_REPORT = 'MATERIAL_CONSUMPTION_REPORT',
  EXPENSE_VOUCHER = 'EXPENSE_VOUCHER',
  PAYMENT_VOUCHER = 'PAYMENT_VOUCHER',
  JOURNAL_ENTRY = 'JOURNAL_ENTRY',
  CUSTOMER_RECEIPT = 'CUSTOMER_RECEIPT',
  PAYMENT_SCHEDULE = 'PAYMENT_SCHEDULE',
  PAYMENT_DEMAND = 'PAYMENT_DEMAND',
  CONTRACTOR_BILL = 'CONTRACTOR_BILL',
  CONTRACTOR_PAYMENT = 'CONTRACTOR_PAYMENT',
  CONTRACTOR_AGREEMENT = 'CONTRACTOR_AGREEMENT',
  LABOUR_CATEGORY = 'LABOUR_CATEGORY',
  LABOUR_ATTENDANCE = 'LABOUR_ATTENDANCE',
  MANPOWER_DAILY_PLAN = 'MANPOWER_DAILY_PLAN',
  CONTRIBUTION_COMMITMENT = 'CONTRIBUTION_COMMITMENT',
  CONTRIBUTION_RECEIPT = 'CONTRIBUTION_RECEIPT',
  DOCUMENT = 'DOCUMENT',
  APPROVAL = 'APPROVAL',
  BANK_ACCOUNT = 'BANK_ACCOUNT',
  CASH_ACCOUNT = 'CASH_ACCOUNT',
  PETTY_CASH_REQUIREMENT = 'PETTY_CASH_REQUIREMENT',
  PETTY_CASH_FUND_TRANSFER = 'PETTY_CASH_FUND_TRANSFER',
}

export type NumberFormatConfig = {
  prefix: string;
  padLength: number;
  /** Include financial/calendar year segment, e.g. PRJ-2026-0001 */
  useFinancialYear: boolean;
  /** Allow counters scoped per project when projectId is provided */
  allowProjectScope: boolean;
};

/**
 * Human-readable code formats for Luxaria documents.
 * Examples: PRJ-2026-0001, VEN-000001, PO-2026-000001, JV-2026-000001
 */
export const NUMBER_FORMATS: Record<NumberEntityType, NumberFormatConfig> = {
  [NumberEntityType.COMPANY]: {
    prefix: 'CMP',
    padLength: 4,
    useFinancialYear: false,
    allowProjectScope: false,
  },
  [NumberEntityType.USER]: {
    prefix: 'USR',
    padLength: 6,
    useFinancialYear: false,
    allowProjectScope: false,
  },
  [NumberEntityType.EMPLOYEE]: {
    prefix: 'EMP',
    padLength: 6,
    useFinancialYear: false,
    allowProjectScope: false,
  },
  [NumberEntityType.ROLE]: {
    prefix: 'ROL',
    padLength: 6,
    useFinancialYear: false,
    allowProjectScope: false,
  },
  [NumberEntityType.PROJECT]: {
    prefix: 'PRJ',
    padLength: 4,
    useFinancialYear: true,
    allowProjectScope: false,
  },
  [NumberEntityType.DIRECTOR]: {
    prefix: 'DIR',
    padLength: 4,
    useFinancialYear: false,
    allowProjectScope: false,
  },
  [NumberEntityType.INVESTOR]: {
    prefix: 'INV',
    padLength: 4,
    useFinancialYear: false,
    allowProjectScope: false,
  },
  [NumberEntityType.VENDOR]: {
    prefix: 'VEN',
    padLength: 6,
    useFinancialYear: false,
    allowProjectScope: false,
  },
  [NumberEntityType.CONTRACTOR]: {
    prefix: 'CON',
    padLength: 6,
    useFinancialYear: false,
    allowProjectScope: false,
  },
  [NumberEntityType.CUSTOMER]: {
    prefix: 'CUS',
    padLength: 6,
    useFinancialYear: false,
    allowProjectScope: false,
  },
  [NumberEntityType.BOOKING]: {
    prefix: 'BK',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.BOOKING_CANCELLATION]: {
    prefix: 'BC',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.MATERIAL]: {
    prefix: 'MAT',
    padLength: 6,
    useFinancialYear: false,
    allowProjectScope: false,
  },
  [NumberEntityType.PURCHASE_REQUEST]: {
    prefix: 'PR',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.RFQ]: {
    prefix: 'RFQ',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.VENDOR_QUOTATION]: {
    prefix: 'VQ',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.QUOTATION_COMPARISON]: {
    prefix: 'QC',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.PURCHASE_ORDER]: {
    prefix: 'PO',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.GOODS_RECEIPT]: {
    prefix: 'GRN',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.QUALITY_INSPECTION]: {
    prefix: 'QI',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.STOCK_LEDGER]: {
    prefix: 'SL',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.STOCK_COUNT]: {
    prefix: 'SC',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.MATERIAL_ISSUE]: {
    prefix: 'MI',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.MATERIAL_RETURN]: {
    prefix: 'MR',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.VENDOR_INVOICE]: {
    prefix: 'VI',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.VENDOR_PAYMENT]: {
    prefix: 'VP',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.BOQ]: {
    prefix: 'BOQ',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.DAILY_PROGRESS_REPORT]: {
    prefix: 'DPR',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.WORK_MEASUREMENT]: {
    prefix: 'WM',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.MATERIAL_CONSUMPTION_STANDARD]: {
    prefix: 'MCS',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: false,
  },
  [NumberEntityType.MATERIAL_CONSUMPTION_REPORT]: {
    prefix: 'MCR',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.EXPENSE_VOUCHER]: {
    prefix: 'EXP',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.PAYMENT_VOUCHER]: {
    prefix: 'PV',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.JOURNAL_ENTRY]: {
    prefix: 'JV',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.CUSTOMER_RECEIPT]: {
    prefix: 'CR',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.PAYMENT_SCHEDULE]: {
    prefix: 'PS',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.PAYMENT_DEMAND]: {
    prefix: 'DM',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.CONTRACTOR_BILL]: {
    prefix: 'CB',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.CONTRACTOR_PAYMENT]: {
    prefix: 'CP',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.CONTRACTOR_AGREEMENT]: {
    prefix: 'CA',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.LABOUR_CATEGORY]: {
    prefix: 'LBC',
    padLength: 6,
    useFinancialYear: false,
    allowProjectScope: false,
  },
  [NumberEntityType.LABOUR_ATTENDANCE]: {
    prefix: 'LAT',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.MANPOWER_DAILY_PLAN]: {
    prefix: 'MPL',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.CONTRIBUTION_COMMITMENT]: {
    prefix: 'COM',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.CONTRIBUTION_RECEIPT]: {
    prefix: 'CTR',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.DOCUMENT]: {
    prefix: 'DOC',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.APPROVAL]: {
    prefix: 'APR',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.BANK_ACCOUNT]: {
    prefix: 'BA',
    padLength: 4,
    useFinancialYear: false,
    allowProjectScope: false,
  },
  [NumberEntityType.CASH_ACCOUNT]: {
    prefix: 'CSH',
    padLength: 4,
    useFinancialYear: false,
    allowProjectScope: true,
  },
  [NumberEntityType.PETTY_CASH_REQUIREMENT]: {
    prefix: 'PCR',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
  [NumberEntityType.PETTY_CASH_FUND_TRANSFER]: {
    prefix: 'PCF',
    padLength: 6,
    useFinancialYear: true,
    allowProjectScope: true,
  },
};
