import { fireEvent, render, screen } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import { ProjectForm } from './ProjectForm';

const company = {
  id: '507f1f77bcf86cd799439012',
  companyCode: 'LUX',
  legalName: 'Luxaria Developers Private Limited',
};

describe('ProjectForm', () => {
  it('keeps company read-only and never exposes projectCode', () => {
    render(
      <ProjectForm
        mode="create"
        company={company}
        onSubmit={vi.fn()}
      />,
    );

    expect(screen.getByLabelText('Company')).toBeDisabled();
    expect(
      screen.queryByRole('textbox', { name: /project code/i }),
    ).not.toBeInTheDocument();
    expect(
      screen.getByText(/project code is generated by the server/i),
    ).toBeInTheDocument();
  });

  it('shows validation errors before submitting incomplete data', async () => {
    const onSubmit = vi.fn();
    render(
      <ProjectForm
        mode="create"
        company={company}
        onSubmit={onSubmit}
      />,
    );

    fireEvent.submit(screen.getByTestId('project-form'));

    expect(
      await screen.findByText('Project name is required'),
    ).toBeInTheDocument();
    expect(onSubmit).not.toHaveBeenCalled();
  });

  it('hides terminal create statuses without close permission', () => {
    render(
      <ProjectForm
        mode="create"
        company={company}
        onSubmit={vi.fn()}
      />,
    );

    fireEvent.mouseDown(screen.getByLabelText('Initial status'));

    expect(
      screen.queryByRole('option', { name: 'Closed' }),
    ).not.toBeInTheDocument();
    expect(
      screen.queryByRole('option', { name: 'Cancelled' }),
    ).not.toBeInTheDocument();
  });

  it('shows terminal create statuses with close permission', () => {
    render(
      <ProjectForm
        mode="create"
        company={company}
        allowTerminalStatus
        onSubmit={vi.fn()}
      />,
    );

    fireEvent.mouseDown(screen.getByLabelText('Initial status'));

    expect(screen.getByRole('option', { name: 'Closed' })).toBeInTheDocument();
    expect(
      screen.getByRole('option', { name: 'Cancelled' }),
    ).toBeInTheDocument();
  });
});
