import type { PermissionCode } from './permissionCatalog';

/** Icon keys resolved in the Sidebar. */
export type NavIconId =
  | 'dashboard'
  | 'projects'
  | 'dpr'
  | 'users'
  | 'settings'
  | 'notifications'
  | 'approvals'
  | 'documents'
  | 'audit'
  | 'finance'
  | 'purchase'
  | 'stock'
  | 'sales'
  | 'reports'
  | 'company';

export type ProjectScopeMode = 'none' | 'required';

export type AppLayoutKind = 'auth' | 'app';

export type NavGroupId =
  | 'overview'
  | 'approvals'
  | 'projects-site'
  | 'project-control'
  | 'procurement'
  | 'contractors'
  | 'capital-investment'
  | 'accounting'
  | 'reports'
  | 'petty-cash'
  | 'inventory'
  | 'sales'
  | 'organisation'
  | 'administration'
  | 'system';

/**
 * Central route metadata (Micro Phase 012).
 * Navigation visibility and route guards both read from this registry.
 */
export type AppRouteDefinition = {
  id: string;
  /** Absolute path, e.g. `/users` or `/`. */
  path: string;
  title: string;
  layout: AppLayoutKind;
  /** When true, include in the sidebar (if groupId set and access allows). */
  showInNav: boolean;
  groupId?: NavGroupId;
  icon?: NavIconId;
  /** Require any of these catalog permissions (from `GET /rbac/me/permissions`). */
  anyOf?: readonly PermissionCode[];
  /** Require all of these catalog permissions. */
  allOf?: readonly PermissionCode[];
  /**
   * `required` → wrap with `ProjectRequiredRoute` (active project + workflow).
   * Hiding nav is not enough; URL access is blocked by the same flag.
   */
  projectScope: ProjectScopeMode;
  /** Exact match for index routes. */
  end?: boolean;
  /** Breadcrumb segment overrides keyed by path segment. */
  breadcrumbSegment?: string;
};

export type NavGroupMeta = {
  id: NavGroupId;
  label: string;
};

export const NAV_GROUP_META: readonly NavGroupMeta[] = [
  { id: 'overview', label: 'Overview' },
  { id: 'approvals', label: 'Approvals' },
  { id: 'projects-site', label: 'Projects & site' },
  { id: 'project-control', label: 'Project Control' },
  { id: 'procurement', label: 'Procurement' },
  { id: 'contractors', label: 'Contractors' },
  { id: 'capital-investment', label: 'Capital & Investment' },
  { id: 'accounting', label: 'Accounting' },
  { id: 'reports', label: 'Accounting reports' },
  { id: 'petty-cash', label: 'Petty Cash' },
  { id: 'inventory', label: 'Inventory' },
  { id: 'sales', label: 'Sales' },
  { id: 'organisation', label: 'Organisation' },
  { id: 'administration', label: 'Administration' },
  { id: 'system', label: 'System' },
] as const;

export class DuplicateRoutePathError extends Error {
  constructor(path: string) {
    super(`Duplicate route path in navigation registry: ${path}`);
    this.name = 'DuplicateRoutePathError';
  }
}

export function assertUniqueRoutePaths(
  routes: readonly AppRouteDefinition[],
): void {
  const seen = new Set<string>();
  for (const route of routes) {
    if (seen.has(route.path)) {
      throw new DuplicateRoutePathError(route.path);
    }
    seen.add(route.path);
  }
}

export function defineRouteRegistry<
  const T extends readonly AppRouteDefinition[],
>(routes: T): T {
  assertUniqueRoutePaths(routes);
  return routes;
}

/**
 * All web routes — existing and placeholders for future modules.
 * Add new portal pages here first; wire the element in `routeElements.tsx`
 * and `AppRouter`.
 */
const APP_ROUTES = [
  {
    id: 'login',
    path: '/login',
    title: 'Sign in',
    layout: 'auth',
    showInNav: false,
    projectScope: 'none',
  },
  {
    id: 'dashboard',
    path: '/',
    title: 'Dashboard',
    layout: 'app',
    showInNav: true,
    groupId: 'overview',
    icon: 'dashboard',
    projectScope: 'none',
    end: true,
  },
  {
    id: 'director-command-centre',
    path: '/dashboard/director',
    title: 'Director Command Centre',
    layout: 'app',
    showInNav: true,
    groupId: 'overview',
    icon: 'reports',
    anyOf: ['dashboard.view'],
    projectScope: 'none',
    breadcrumbSegment: 'director',
  },
  {
    id: 'finance-dashboard',
    path: '/dashboard/finance',
    title: 'Finance',
    layout: 'app',
    showInNav: true,
    groupId: 'overview',
    icon: 'finance',
    anyOf: ['dashboard.view'],
    projectScope: 'none',
    breadcrumbSegment: 'finance',
  },
  {
    id: 'site-operations-dashboard',
    path: '/dashboard/site',
    title: 'Site Operations',
    layout: 'app',
    showInNav: true,
    groupId: 'overview',
    icon: 'dpr',
    anyOf: ['dashboard.view'],
    projectScope: 'required',
    breadcrumbSegment: 'site',
  },
  {
    id: 'site-execution-dashboard',
    path: '/site-execution/dashboard',
    title: 'Site Execution',
    layout: 'app',
    showInNav: true,
    groupId: 'overview',
    icon: 'dpr',
    anyOf: ['dashboard.view'],
    projectScope: 'required',
    breadcrumbSegment: 'dashboard',
  },
  {
    id: 'site-execution-reports',
    path: '/site-execution/reports',
    title: 'Site Execution Reports',
    layout: 'app',
    showInNav: true,
    groupId: 'overview',
    icon: 'reports',
    anyOf: ['dashboard.view'],
    projectScope: 'required',
    breadcrumbSegment: 'reports',
  },
  {
    id: 'purchase-dashboard',
    path: '/dashboard/purchase',
    title: 'Purchase',
    layout: 'app',
    showInNav: true,
    groupId: 'overview',
    icon: 'purchase',
    anyOf: ['dashboard.view'],
    projectScope: 'required',
    breadcrumbSegment: 'purchase',
  },
  {
    id: 'notifications',
    path: '/notifications',
    title: 'Notifications',
    layout: 'app',
    showInNav: true,
    groupId: 'overview',
    icon: 'notifications',
    anyOf: ['notification.view'],
    projectScope: 'none',
  },
  {
    id: 'approvals',
    path: '/approvals',
    title: 'Pending',
    layout: 'app',
    showInNav: true,
    groupId: 'approvals',
    icon: 'approvals',
    anyOf: ['approval.view'],
    projectScope: 'required',
  },
  {
    id: 'approval-detail',
    path: '/approvals/:approvalId',
    title: 'Approval',
    layout: 'app',
    showInNav: false,
    anyOf: ['approval.view'],
    projectScope: 'required',
    breadcrumbSegment: 'approvals',
  },
  {
    id: 'projects',
    path: '/projects',
    title: 'Projects',
    layout: 'app',
    showInNav: true,
    groupId: 'projects-site',
    icon: 'projects',
    anyOf: ['project.view'],
    projectScope: 'none',
  },
  {
    id: 'project-create',
    path: '/projects/new',
    title: 'New Project',
    layout: 'app',
    showInNav: false,
    anyOf: ['project.create'],
    projectScope: 'none',
    breadcrumbSegment: 'projects',
  },
  {
    id: 'project-detail',
    path: '/projects/:projectId',
    title: 'Project',
    layout: 'app',
    showInNav: false,
    anyOf: ['project.view'],
    projectScope: 'none',
    breadcrumbSegment: 'projects',
  },
  {
    id: 'project-edit',
    path: '/projects/:projectId/edit',
    title: 'Edit Project',
    layout: 'app',
    showInNav: false,
    allOf: ['project.view', 'project.update'],
    projectScope: 'none',
    breadcrumbSegment: 'projects',
  },
  {
    id: 'project-access',
    path: '/projects/:projectId/access',
    title: 'Project Access',
    layout: 'app',
    showInNav: false,
    anyOf: ['project_access.view'],
    projectScope: 'none',
    breadcrumbSegment: 'projects',
  },
  {
    id: 'project-documents',
    path: '/projects/:projectId/documents',
    title: 'Project Documents',
    layout: 'app',
    showInNav: false,
    anyOf: ['project.view'],
    projectScope: 'none',
    breadcrumbSegment: 'projects',
  },
  {
    id: 'project-settings',
    path: '/projects/:projectId/settings',
    title: 'Project Settings',
    layout: 'app',
    showInNav: false,
    allOf: ['project.view', 'project.update'],
    projectScope: 'none',
    breadcrumbSegment: 'projects',
  },
  {
    id: 'project-structure',
    path: '/projects/:projectId/structure',
    title: 'Project Structure',
    layout: 'app',
    showInNav: false,
    anyOf: ['project.view', 'site.view'],
    projectScope: 'none',
    breadcrumbSegment: 'projects',
  },
  {
    id: 'project-team',
    path: '/projects/:projectId/team',
    title: 'Project Team',
    layout: 'app',
    showInNav: false,
    anyOf: ['project.view', 'project_access.view'],
    projectScope: 'none',
    breadcrumbSegment: 'projects',
  },
  {
    id: 'project-warehouses',
    path: '/projects/:projectId/warehouses',
    title: 'Project Warehouses',
    layout: 'app',
    showInNav: false,
    anyOf: ['project.view', 'site.view'],
    projectScope: 'none',
    breadcrumbSegment: 'projects',
  },
  {
    id: 'project-financial-settings',
    path: '/projects/:projectId/financial-settings',
    title: 'Project Financial Settings',
    layout: 'app',
    showInNav: false,
    allOf: ['project.view', 'project.update'],
    projectScope: 'none',
    breadcrumbSegment: 'projects',
  },
  {
    id: 'project-dashboard',
    path: '/projects/dashboard',
    title: 'Project Dashboard',
    layout: 'app',
    showInNav: true,
    groupId: 'projects-site',
    icon: 'reports',
    anyOf: ['dashboard.view'],
    projectScope: 'required',
    breadcrumbSegment: 'dashboard',
  },
  {
    id: 'project-dashboard-detail',
    path: '/projects/:projectId/dashboard',
    title: 'Project Dashboard',
    layout: 'app',
    showInNav: false,
    anyOf: ['dashboard.view'],
    projectScope: 'required',
    breadcrumbSegment: 'dashboard',
  },
  {
    id: 'project-participants',
    path: '/projects/participants',
    title: 'Participants',
    layout: 'app',
    showInNav: true,
    groupId: 'projects-site',
    icon: 'finance',
    anyOf: ['project_participant.view'],
    projectScope: 'required',
    breadcrumbSegment: 'participants',
  },
  {
    id: 'project-participants-detail',
    path: '/projects/:projectId/participants',
    title: 'Participants',
    layout: 'app',
    showInNav: false,
    anyOf: ['project_participant.view'],
    projectScope: 'required',
    breadcrumbSegment: 'participants',
  },
  {
    id: 'profit-share',
    path: '/projects/profit-share',
    title: 'Profit Share',
    layout: 'app',
    showInNav: true,
    groupId: 'projects-site',
    icon: 'finance',
    anyOf: ['project_participant.view'],
    projectScope: 'required',
    breadcrumbSegment: 'profit-share',
  },
  {
    id: 'profit-share-detail',
    path: '/projects/:projectId/profit-share',
    title: 'Profit Share',
    layout: 'app',
    showInNav: false,
    anyOf: ['project_participant.view'],
    projectScope: 'required',
    breadcrumbSegment: 'profit-share',
  },
  {
    id: 'daily-progress',
    path: '/project-control/dpr',
    title: 'Daily progress',
    layout: 'app',
    showInNav: true,
    groupId: 'project-control',
    icon: 'dpr',
    anyOf: ['dpr.view'],
    projectScope: 'required',
    breadcrumbSegment: 'dpr',
  },
  {
    id: 'dpr-detail',
    path: '/project-control/dpr/:id',
    title: 'Daily progress report',
    layout: 'app',
    showInNav: false,
    anyOf: ['dpr.view'],
    projectScope: 'required',
    breadcrumbSegment: 'dpr',
  },
  {
    id: 'boq',
    path: '/project-control/boq',
    title: 'BOQ',
    layout: 'app',
    showInNav: true,
    groupId: 'project-control',
    icon: 'projects',
    anyOf: ['boq.view'],
    projectScope: 'required',
    breadcrumbSegment: 'boq',
  },
  {
    id: 'boq-import',
    path: '/project-control/boq/import',
    title: 'Import BOQ',
    layout: 'app',
    showInNav: false,
    anyOf: ['boq.manage'],
    projectScope: 'required',
    breadcrumbSegment: 'boq',
  },
  {
    id: 'work-measurements',
    path: '/project-control/work-measurements',
    title: 'Work Measurements',
    layout: 'app',
    showInNav: true,
    groupId: 'project-control',
    icon: 'projects',
    anyOf: ['measurement.view'],
    projectScope: 'required',
    breadcrumbSegment: 'work-measurements',
  },
  {
    id: 'measurement-book',
    path: '/measurements',
    title: 'Measurement Book',
    layout: 'app',
    showInNav: true,
    groupId: 'contractors',
    icon: 'projects',
    anyOf: ['measurement.view'],
    projectScope: 'required',
    breadcrumbSegment: 'measurements',
  },
  {
    id: 'material-reconciliation',
    path: '/material-reconciliation',
    title: 'Material Reconciliation',
    layout: 'app',
    showInNav: true,
    groupId: 'contractors',
    icon: 'stock',
    anyOf: ['contractor_recovery.view'],
    projectScope: 'required',
    breadcrumbSegment: 'material-reconciliation',
  },
  {
    id: 'retention-register',
    path: '/retention-register',
    title: 'Retention Register',
    layout: 'app',
    showInNav: true,
    groupId: 'contractors',
    icon: 'finance',
    anyOf: ['contractor_retention.view'],
    projectScope: 'required',
    breadcrumbSegment: 'retention-register',
  },
  {
    id: 'contractor-ledger',
    path: '/contractor-ledger',
    title: 'Contractor Ledger',
    layout: 'app',
    showInNav: true,
    groupId: 'contractors',
    icon: 'finance',
    anyOf: ['report.view'],
    projectScope: 'required',
    breadcrumbSegment: 'contractor-ledger',
  },
  {
    id: 'drawings',
    path: '/project-control/drawings',
    title: 'Drawings',
    layout: 'app',
    showInNav: true,
    groupId: 'project-control',
    icon: 'projects',
    anyOf: ['drawing.view'],
    projectScope: 'required',
    breadcrumbSegment: 'drawings',
  },
  {
    id: 'equipment',
    path: '/project-control/equipment',
    title: 'Equipment',
    layout: 'app',
    showInNav: true,
    groupId: 'project-control',
    icon: 'projects',
    anyOf: ['equipment.view'],
    projectScope: 'required',
    breadcrumbSegment: 'equipment',
  },
  {
    id: 'site-quality',
    path: '/project-control/site-quality',
    title: 'Site Quality',
    layout: 'app',
    showInNav: true,
    groupId: 'project-control',
    icon: 'projects',
    anyOf: ['site_quality.view'],
    projectScope: 'required',
    breadcrumbSegment: 'site-quality',
  },
  {
    id: 'site-safety',
    path: '/project-control/site-safety',
    title: 'Site Safety',
    layout: 'app',
    showInNav: true,
    groupId: 'project-control',
    icon: 'projects',
    anyOf: ['safety.view'],
    projectScope: 'required',
    breadcrumbSegment: 'site-safety',
  },
  {
    id: 'site-issues',
    path: '/project-control/site-issues',
    title: 'Site Issues',
    layout: 'app',
    showInNav: true,
    groupId: 'project-control',
    icon: 'projects',
    anyOf: ['site_issue.view'],
    projectScope: 'required',
    breadcrumbSegment: 'site-issues',
  },
  {
    id: 'site-diary',
    path: '/project-control/site-diary',
    title: 'Site Diary',
    layout: 'app',
    showInNav: true,
    groupId: 'project-control',
    icon: 'projects',
    anyOf: ['site_diary.view'],
    projectScope: 'required',
    breadcrumbSegment: 'site-diary',
  },
  {
    id: 'material-coefficients',
    path: '/project-control/material-coefficients',
    title: 'Material Coefficients',
    layout: 'app',
    showInNav: true,
    groupId: 'project-control',
    icon: 'stock',
    anyOf: ['material_consumption.view'],
    projectScope: 'none',
    breadcrumbSegment: 'material-coefficients',
  },
  {
    id: 'material-variance',
    path: '/project-control/material-variance',
    title: 'Material Variance',
    layout: 'app',
    showInNav: true,
    groupId: 'project-control',
    icon: 'stock',
    anyOf: ['material_consumption.view'],
    projectScope: 'required',
    breadcrumbSegment: 'material-variance',
  },
  {
    id: 'cost-forecast',
    path: '/project-control/cost-forecast',
    title: 'Cost Forecast',
    layout: 'app',
    showInNav: true,
    groupId: 'project-control',
    icon: 'reports',
    allOf: ['report.view', 'dashboard.view'],
    projectScope: 'required',
    breadcrumbSegment: 'cost-forecast',
  },
  {
    id: 'vendors',
    path: '/procurement/vendors',
    title: 'Vendors',
    layout: 'app',
    showInNav: true,
    groupId: 'procurement',
    icon: 'purchase',
    anyOf: ['vendor.view'],
    projectScope: 'none',
    breadcrumbSegment: 'vendors',
  },
  {
    id: 'vendor-detail',
    path: '/procurement/vendors/:vendorId',
    title: 'Vendor',
    layout: 'app',
    showInNav: false,
    anyOf: ['vendor.view'],
    projectScope: 'none',
    breadcrumbSegment: 'vendors',
  },
  {
    id: 'contractors',
    path: '/contractors',
    title: 'Contractors',
    layout: 'app',
    showInNav: true,
    groupId: 'contractors',
    icon: 'users',
    anyOf: ['contractor.view'],
    projectScope: 'none',
    breadcrumbSegment: 'contractors',
  },
  {
    id: 'contractor-dashboard',
    path: '/contractors/dashboard',
    title: 'Contractor Dashboard',
    layout: 'app',
    showInNav: true,
    groupId: 'contractors',
    icon: 'reports',
    anyOf: ['dashboard.view', 'contractor.view'],
    projectScope: 'required',
    breadcrumbSegment: 'dashboard',
  },
  {
    id: 'contractor-reports',
    path: '/contractors/reports',
    title: 'Contractor Reports',
    layout: 'app',
    showInNav: true,
    groupId: 'contractors',
    icon: 'reports',
    anyOf: ['contractor_report.view', 'contractor.view'],
    projectScope: 'required',
    breadcrumbSegment: 'reports',
  },
  {
    id: 'contractor-compliance',
    path: '/contractors/compliance',
    title: 'Contractor Compliance',
    layout: 'app',
    showInNav: true,
    groupId: 'contractors',
    icon: 'users',
    anyOf: ['contractor.view'],
    projectScope: 'none',
    breadcrumbSegment: 'compliance',
  },
  {
    id: 'contractor-tenders',
    path: '/contractor-tenders',
    title: 'Tenders',
    layout: 'app',
    showInNav: true,
    groupId: 'contractors',
    icon: 'documents',
    anyOf: ['tender.view'],
    projectScope: 'required',
    breadcrumbSegment: 'tenders',
  },
  {
    id: 'rate-contracts',
    path: '/rate-contracts',
    title: 'Rate Contracts',
    layout: 'app',
    showInNav: true,
    groupId: 'contractors',
    icon: 'documents',
    anyOf: ['rate_contract.view'],
    projectScope: 'none',
    breadcrumbSegment: 'rate-contracts',
  },
  {
    id: 'work-orders',
    path: '/work-orders',
    title: 'Work Orders',
    layout: 'app',
    showInNav: true,
    groupId: 'contractors',
    icon: 'projects',
    anyOf: ['work_order.view'],
    projectScope: 'required',
    breadcrumbSegment: 'work-orders',
  },
  {
    id: 'work-order-detail',
    path: '/work-orders/:id',
    title: 'Work Order',
    layout: 'app',
    showInNav: false,
    anyOf: ['work_order.view'],
    projectScope: 'required',
    breadcrumbSegment: 'work-orders',
  },
  {
    id: 'contractor-tender-compare',
    path: '/contractor-tenders/:id/compare',
    title: 'Bid comparison',
    layout: 'app',
    showInNav: false,
    anyOf: ['tender.view'],
    projectScope: 'required',
    breadcrumbSegment: 'compare',
  },
  {
    id: 'contractor-agreements',
    path: '/contractors/agreements',
    title: 'Agreements',
    layout: 'app',
    showInNav: true,
    groupId: 'contractors',
    icon: 'documents',
    anyOf: ['contractor_agreement.view'],
    projectScope: 'required',
    breadcrumbSegment: 'agreements',
  },
  {
    id: 'contractor-agreement-detail',
    path: '/contractors/agreements/:agreementId',
    title: 'Agreement',
    layout: 'app',
    showInNav: false,
    anyOf: ['contractor_agreement.view'],
    projectScope: 'required',
    breadcrumbSegment: 'agreements',
  },
  {
    id: 'contractor-payments',
    path: '/contractors/payments',
    title: 'Payments',
    layout: 'app',
    showInNav: true,
    groupId: 'contractors',
    icon: 'finance',
    anyOf: ['payment.view'],
    projectScope: 'required',
    breadcrumbSegment: 'payments',
  },
  {
    id: 'running-bills',
    path: '/contractors/running-bills',
    title: 'Running Bills',
    layout: 'app',
    showInNav: true,
    groupId: 'contractors',
    icon: 'finance',
    anyOf: ['running_bill.view'],
    projectScope: 'required',
    breadcrumbSegment: 'running-bills',
  },
  {
    id: 'running-bill-create',
    path: '/contractors/running-bills/new',
    title: 'New Running Bill',
    layout: 'app',
    showInNav: false,
    anyOf: ['running_bill.create'],
    projectScope: 'required',
    breadcrumbSegment: 'running-bills',
  },
  {
    id: 'running-bill-detail',
    path: '/contractors/running-bills/:id',
    title: 'Running Bill',
    layout: 'app',
    showInNav: false,
    anyOf: ['running_bill.view'],
    projectScope: 'required',
    breadcrumbSegment: 'running-bills',
  },
  {
    id: 'labour-categories',
    path: '/contractors/labour-categories',
    title: 'Labour Categories',
    layout: 'app',
    showInNav: true,
    groupId: 'contractors',
    icon: 'users',
    anyOf: ['labour_category.view'],
    projectScope: 'none',
    breadcrumbSegment: 'labour-categories',
  },
  {
    id: 'labour-attendance',
    path: '/contractors/attendance',
    title: 'Attendance',
    layout: 'app',
    showInNav: true,
    groupId: 'contractors',
    icon: 'dpr',
    anyOf: ['attendance.view'],
    projectScope: 'required',
    breadcrumbSegment: 'attendance',
  },
  {
    id: 'signed-payment-vouchers',
    path: '/contractors/signed-vouchers',
    title: 'Signed Vouchers',
    layout: 'app',
    showInNav: true,
    groupId: 'contractors',
    icon: 'dpr',
    anyOf: ['payment.view'],
    projectScope: 'required',
    breadcrumbSegment: 'signed-vouchers',
  },
  {
    id: 'signed-payment-voucher-detail',
    path: '/contractors/signed-vouchers/:voucherId',
    title: 'Signed Voucher',
    layout: 'app',
    showInNav: false,
    anyOf: ['payment.view'],
    projectScope: 'required',
    breadcrumbSegment: 'signed-vouchers',
  },
  {
    id: 'manpower-shortfall',
    path: '/contractors/manpower-shortfall',
    title: 'Manpower Shortfall',
    layout: 'app',
    showInNav: true,
    groupId: 'contractors',
    icon: 'reports',
    anyOf: ['manpower_shortfall.view'],
    projectScope: 'required',
    breadcrumbSegment: 'manpower-shortfall',
  },
  {
    id: 'manpower-plans',
    path: '/contractors/manpower-plans',
    title: 'Manpower Plans',
    layout: 'app',
    showInNav: true,
    groupId: 'contractors',
    icon: 'reports',
    anyOf: ['manpower_plan.view'],
    projectScope: 'required',
    breadcrumbSegment: 'manpower-plans',
  },
  {
    id: 'manpower-plan-detail',
    path: '/contractors/manpower-plans/:planId',
    title: 'Manpower Plan',
    layout: 'app',
    showInNav: false,
    anyOf: ['manpower_plan.view'],
    projectScope: 'required',
    breadcrumbSegment: 'manpower-plans',
  },
  {
    id: 'contractor-detail',
    path: '/contractors/:contractorId',
    title: 'Contractor',
    layout: 'app',
    showInNav: false,
    anyOf: ['contractor.view'],
    projectScope: 'none',
    breadcrumbSegment: 'contractors',
  },
  {
    id: 'sales-dashboard',
    path: '/sales/dashboard',
    title: 'Sales Dashboard',
    layout: 'app',
    showInNav: true,
    groupId: 'sales',
    icon: 'sales',
    anyOf: ['sales_report.view'],
    projectScope: 'none',
    breadcrumbSegment: 'dashboard',
  },
  {
    id: 'leads',
    path: '/sales/leads',
    title: 'Leads',
    layout: 'app',
    showInNav: true,
    groupId: 'sales',
    icon: 'sales',
    anyOf: ['lead.view'],
    projectScope: 'none',
    breadcrumbSegment: 'leads',
  },
  {
    id: 'lead-detail',
    path: '/sales/leads/:leadId',
    title: 'Lead',
    layout: 'app',
    showInNav: false,
    anyOf: ['lead.view'],
    projectScope: 'none',
    breadcrumbSegment: 'leads',
  },
  {
    id: 'unit-quotations',
    path: '/sales/quotations',
    title: 'Unit Quotations',
    layout: 'app',
    showInNav: true,
    groupId: 'sales',
    icon: 'sales',
    anyOf: ['quotation.view'],
    projectScope: 'required',
    breadcrumbSegment: 'quotations',
  },
  {
    id: 'sale-agreements',
    path: '/sales/agreements',
    title: 'Sale Agreements',
    layout: 'app',
    showInNav: true,
    groupId: 'sales',
    icon: 'sales',
    anyOf: ['agreement.view'],
    projectScope: 'required',
    breadcrumbSegment: 'agreements',
  },
  {
    id: 'customer-loans',
    path: '/sales/loans',
    title: 'Customer Loans',
    layout: 'app',
    showInNav: true,
    groupId: 'sales',
    icon: 'sales',
    anyOf: ['loan.view'],
    projectScope: 'required',
    breadcrumbSegment: 'loans',
  },
  {
    id: 'unit-registrations',
    path: '/sales/registrations',
    title: 'Unit Registrations',
    layout: 'app',
    showInNav: true,
    groupId: 'sales',
    icon: 'sales',
    anyOf: ['registration.view'],
    projectScope: 'required',
    breadcrumbSegment: 'registrations',
  },
  {
    id: 'unit-handovers',
    path: '/sales/handovers',
    title: 'Unit Handovers',
    layout: 'app',
    showInNav: true,
    groupId: 'sales',
    icon: 'sales',
    anyOf: ['handover.view'],
    projectScope: 'required',
    breadcrumbSegment: 'handovers',
  },
  {
    id: 'customer-warranties',
    path: '/sales/warranties',
    title: 'Customer Warranties',
    layout: 'app',
    showInNav: true,
    groupId: 'sales',
    icon: 'sales',
    anyOf: ['warranty.view'],
    projectScope: 'required',
    breadcrumbSegment: 'warranties',
  },
  {
    id: 'customer-portal',
    path: '/sales/customer-portal',
    title: 'Customer Portal',
    layout: 'app',
    showInNav: true,
    groupId: 'sales',
    icon: 'sales',
    anyOf: ['customer_portal.view'],
    projectScope: 'none',
    breadcrumbSegment: 'customer-portal',
  },
  {
    id: 'customers',
    path: '/sales/customers',
    title: 'Customers',
    layout: 'app',
    showInNav: true,
    groupId: 'sales',
    icon: 'sales',
    anyOf: ['customer.view'],
    projectScope: 'none',
    breadcrumbSegment: 'customers',
  },
  {
    id: 'customer-detail',
    path: '/sales/customers/:customerId',
    title: 'Customer',
    layout: 'app',
    showInNav: false,
    anyOf: ['customer.view'],
    projectScope: 'none',
    breadcrumbSegment: 'customers',
  },
  {
    id: 'purchase-orders',
    path: '/procurement/purchase-orders',
    title: 'Purchase Orders',
    layout: 'app',
    showInNav: true,
    groupId: 'procurement',
    icon: 'purchase',
    anyOf: ['purchase.view'],
    projectScope: 'required',
    breadcrumbSegment: 'purchase-orders',
  },
  {
    id: 'purchase-order-create',
    path: '/procurement/purchase-orders/new',
    title: 'New Purchase Order',
    layout: 'app',
    showInNav: false,
    anyOf: ['purchase.order'],
    projectScope: 'required',
    breadcrumbSegment: 'purchase-orders',
  },
  {
    id: 'purchase-order-detail',
    path: '/procurement/purchase-orders/:purchaseOrderId',
    title: 'Purchase Order',
    layout: 'app',
    showInNav: false,
    anyOf: ['purchase.view'],
    projectScope: 'required',
    breadcrumbSegment: 'purchase-orders',
  },
  {
    id: 'procurement-masters',
    path: '/procurement/masters',
    title: 'Procurement Masters',
    layout: 'app',
    showInNav: true,
    groupId: 'procurement',
    icon: 'purchase',
    anyOf: ['procurement_master.view'],
    projectScope: 'none',
    breadcrumbSegment: 'masters',
  },
  {
    id: 'rfq-list',
    path: '/procurement/rfqs',
    title: 'RFQs',
    layout: 'app',
    showInNav: true,
    groupId: 'procurement',
    icon: 'purchase',
    anyOf: ['quotation.view'],
    projectScope: 'required',
    breadcrumbSegment: 'rfqs',
  },
  {
    id: 'rfq-detail',
    path: '/procurement/rfqs/:rfqId',
    title: 'RFQ',
    layout: 'app',
    showInNav: false,
    anyOf: ['quotation.view'],
    projectScope: 'required',
    breadcrumbSegment: 'rfqs',
  },
  {
    id: 'vendor-portal-rfqs',
    path: '/vendor-portal/rfqs',
    title: 'Vendor RFQs',
    layout: 'app',
    showInNav: false,
    anyOf: ['vendor_portal.view'],
    projectScope: 'none',
    breadcrumbSegment: 'vendor-portal',
  },
  {
    id: 'purchase-requests',
    path: '/procurement/purchase-requests',
    title: 'Purchase Requests',
    layout: 'app',
    showInNav: true,
    groupId: 'procurement',
    icon: 'purchase',
    anyOf: ['purchase.view'],
    projectScope: 'required',
    breadcrumbSegment: 'purchase-requests',
  },
  {
    id: 'purchase-request-create',
    path: '/procurement/purchase-requests/new',
    title: 'New Purchase Request',
    layout: 'app',
    showInNav: false,
    anyOf: ['purchase.request'],
    projectScope: 'required',
    breadcrumbSegment: 'purchase-requests',
  },
  {
    id: 'purchase-request-detail',
    path: '/procurement/purchase-requests/:requestId',
    title: 'Purchase Request',
    layout: 'app',
    showInNav: false,
    anyOf: ['purchase.view'],
    projectScope: 'required',
    breadcrumbSegment: 'purchase-requests',
  },
  {
    id: 'quotations',
    path: '/procurement/quotations',
    title: 'Quotations',
    layout: 'app',
    showInNav: true,
    groupId: 'procurement',
    icon: 'purchase',
    anyOf: ['quotation.view'],
    projectScope: 'required',
    breadcrumbSegment: 'quotations',
  },
  {
    id: 'quotation-comparison',
    path: '/procurement/quotation-comparisons/:prId',
    title: 'Quotation Comparison',
    layout: 'app',
    showInNav: false,
    anyOf: ['quotation.compare'],
    projectScope: 'required',
    breadcrumbSegment: 'quotation-comparisons',
  },
  {
    id: 'vendor-invoices',
    path: '/procurement/vendor-invoices',
    title: 'Vendor Invoices',
    layout: 'app',
    showInNav: true,
    groupId: 'procurement',
    icon: 'purchase',
    anyOf: ['vendor_invoice.view'],
    projectScope: 'required',
    breadcrumbSegment: 'vendor-invoices',
  },
  {
    id: 'vendor-invoice-match',
    path: '/procurement/vendor-invoices/:invoiceId/match',
    title: 'Three-way Match',
    layout: 'app',
    showInNav: false,
    anyOf: ['vendor_invoice.view'],
    projectScope: 'required',
    breadcrumbSegment: 'vendor-invoices',
  },
  {
    id: 'vendor-payments',
    path: '/procurement/vendor-payments',
    title: 'Vendor Payments',
    layout: 'app',
    showInNav: true,
    groupId: 'procurement',
    icon: 'purchase',
    anyOf: ['payment.view'],
    projectScope: 'required',
    breadcrumbSegment: 'vendor-payments',
  },
  {
    id: 'inventory-dashboard',
    path: '/inventory/dashboard',
    title: 'Inventory Dashboard',
    layout: 'app',
    showInNav: true,
    groupId: 'inventory',
    icon: 'stock',
    anyOf: ['stock.view'],
    projectScope: 'required',
    breadcrumbSegment: 'dashboard',
  },
  {
    id: 'materials',
    path: '/inventory/materials',
    title: 'Materials',
    layout: 'app',
    showInNav: true,
    groupId: 'inventory',
    icon: 'stock',
    anyOf: ['material.view'],
    projectScope: 'none',
    breadcrumbSegment: 'materials',
  },
  {
    id: 'material-detail',
    path: '/inventory/materials/:materialId',
    title: 'Material',
    layout: 'app',
    showInNav: false,
    anyOf: ['material.view'],
    projectScope: 'none',
    breadcrumbSegment: 'materials',
  },
  {
    id: 'stock-balances',
    path: '/inventory/stock-balances',
    title: 'Stock Balances',
    layout: 'app',
    showInNav: true,
    groupId: 'inventory',
    icon: 'stock',
    anyOf: ['stock.view'],
    projectScope: 'required',
    breadcrumbSegment: 'stock-balances',
  },
  {
    id: 'stock-ledger',
    path: '/inventory/stock-ledger',
    title: 'Stock Ledger',
    layout: 'app',
    showInNav: true,
    groupId: 'inventory',
    icon: 'stock',
    anyOf: ['stock.view'],
    projectScope: 'required',
    breadcrumbSegment: 'stock-ledger',
  },
  {
    id: 'stock-counts',
    path: '/inventory/stock-counts',
    title: 'Stock Counts',
    layout: 'app',
    showInNav: true,
    groupId: 'inventory',
    icon: 'stock',
    anyOf: ['stock.view'],
    projectScope: 'required',
    breadcrumbSegment: 'stock-counts',
  },
  {
    id: 'stock-count-detail',
    path: '/inventory/stock-counts/:countId',
    title: 'Stock Count',
    layout: 'app',
    showInNav: false,
    anyOf: ['stock.view'],
    projectScope: 'required',
    breadcrumbSegment: 'stock-counts',
  },
  {
    id: 'stock-transfers',
    path: '/inventory/stock-transfers',
    title: 'Stock Transfers',
    layout: 'app',
    showInNav: true,
    groupId: 'inventory',
    icon: 'stock',
    anyOf: ['stock.view'],
    projectScope: 'required',
    breadcrumbSegment: 'stock-transfers',
  },
  {
    id: 'inventory-reports',
    path: '/inventory/reports',
    title: 'Inventory Reports',
    layout: 'app',
    showInNav: true,
    groupId: 'inventory',
    icon: 'stock',
    anyOf: ['stock.view'],
    projectScope: 'required',
    breadcrumbSegment: 'reports',
  },
  {
    id: 'units',
    path: '/sales/units',
    title: 'Units',
    layout: 'app',
    showInNav: true,
    groupId: 'sales',
    icon: 'sales',
    anyOf: ['unit.view'],
    projectScope: 'required',
    breadcrumbSegment: 'units',
  },
  {
    id: 'unit-detail',
    path: '/sales/units/:id',
    title: 'Unit',
    layout: 'app',
    showInNav: false,
    anyOf: ['unit.view'],
    projectScope: 'required',
    breadcrumbSegment: 'units',
  },
  {
    id: 'collections',
    path: '/sales/collections',
    title: 'Collections',
    layout: 'app',
    showInNav: true,
    groupId: 'sales',
    icon: 'sales',
    anyOf: ['collection.view'],
    projectScope: 'required',
    breadcrumbSegment: 'collections',
  },
  {
    id: 'payment-schedules',
    path: '/sales/payment-schedules',
    title: 'Payment Schedules',
    layout: 'app',
    showInNav: true,
    groupId: 'sales',
    icon: 'sales',
    anyOf: ['collection.view'],
    projectScope: 'required',
    breadcrumbSegment: 'payment-schedules',
  },
  {
    id: 'payment-schedule-detail',
    path: '/sales/payment-schedules/:id',
    title: 'Payment Schedule',
    layout: 'app',
    showInNav: false,
    anyOf: ['collection.view'],
    projectScope: 'required',
    breadcrumbSegment: 'payment-schedules',
  },
  {
    id: 'bookings',
    path: '/sales/bookings',
    title: 'Bookings',
    layout: 'app',
    showInNav: true,
    groupId: 'sales',
    icon: 'sales',
    anyOf: ['booking.view'],
    projectScope: 'required',
    breadcrumbSegment: 'bookings',
  },
  {
    id: 'booking-create',
    path: '/sales/bookings/new',
    title: 'New Booking',
    layout: 'app',
    showInNav: false,
    anyOf: ['booking.create'],
    projectScope: 'required',
    breadcrumbSegment: 'bookings',
  },
  {
    id: 'booking-detail',
    path: '/sales/bookings/:bookingId',
    title: 'Booking',
    layout: 'app',
    showInNav: false,
    anyOf: ['booking.view'],
    projectScope: 'required',
    breadcrumbSegment: 'bookings',
  },
  {
    id: 'cancellations',
    path: '/sales/cancellations',
    title: 'Cancellations & Refunds',
    layout: 'app',
    showInNav: true,
    groupId: 'sales',
    icon: 'sales',
    anyOf: ['booking.view'],
    projectScope: 'required',
    breadcrumbSegment: 'cancellations',
  },
  {
    id: 'directors',
    path: '/capital/directors',
    title: 'Directors',
    layout: 'app',
    showInNav: true,
    groupId: 'capital-investment',
    icon: 'company',
    anyOf: ['director.view'],
    projectScope: 'none',
    breadcrumbSegment: 'directors',
  },
  {
    id: 'director-detail',
    path: '/capital/directors/:directorId',
    title: 'Director',
    layout: 'app',
    showInNav: false,
    anyOf: ['director.view'],
    projectScope: 'none',
    breadcrumbSegment: 'directors',
  },
  {
    id: 'shareholding',
    path: '/capital/shareholding',
    title: 'Shareholding',
    layout: 'app',
    showInNav: true,
    groupId: 'capital-investment',
    icon: 'finance',
    anyOf: ['shareholding.view'],
    projectScope: 'none',
    breadcrumbSegment: 'shareholding',
  },
  {
    id: 'investors',
    path: '/capital/investors',
    title: 'Investors',
    layout: 'app',
    showInNav: true,
    groupId: 'capital-investment',
    icon: 'finance',
    anyOf: ['investor.view'],
    projectScope: 'none',
    breadcrumbSegment: 'investors',
  },
  {
    id: 'funding-dashboard',
    path: '/capital/funding-dashboard',
    title: 'Funding Dashboard',
    layout: 'app',
    showInNav: true,
    groupId: 'capital-investment',
    icon: 'finance',
    anyOf: ['dashboard.view'],
    projectScope: 'required',
    breadcrumbSegment: 'funding-dashboard',
  },
  {
    id: 'commitments',
    path: '/capital/commitments',
    title: 'Commitments',
    layout: 'app',
    showInNav: true,
    groupId: 'capital-investment',
    icon: 'finance',
    anyOf: ['contribution_commitment.view'],
    projectScope: 'required',
    breadcrumbSegment: 'commitments',
  },
  {
    id: 'contribution-receipts',
    path: '/capital/contribution-receipts',
    title: 'Contribution Receipts',
    layout: 'app',
    showInNav: true,
    groupId: 'capital-investment',
    icon: 'finance',
    anyOf: ['contribution_receipt.view'],
    projectScope: 'required',
    breadcrumbSegment: 'contribution-receipts',
  },
  {
    id: 'commitment-detail',
    path: '/capital/commitments/:commitmentId',
    title: 'Commitment',
    layout: 'app',
    showInNav: false,
    anyOf: ['contribution_commitment.view'],
    projectScope: 'required',
    breadcrumbSegment: 'commitments',
  },
  {
    id: 'investor-detail',
    path: '/capital/investors/:investorId',
    title: 'Investor',
    layout: 'app',
    showInNav: false,
    anyOf: ['investor.view'],
    projectScope: 'none',
    breadcrumbSegment: 'investors',
  },
  {
    id: 'chart-of-accounts',
    path: '/accounting/chart-of-accounts',
    title: 'Chart of Accounts',
    layout: 'app',
    showInNav: true,
    groupId: 'accounting',
    icon: 'finance',
    anyOf: ['account.view'],
    projectScope: 'none',
    breadcrumbSegment: 'chart-of-accounts',
  },
  {
    id: 'account-create',
    path: '/accounting/chart-of-accounts/new',
    title: 'New account',
    layout: 'app',
    showInNav: false,
    anyOf: ['account.manage'],
    projectScope: 'none',
    breadcrumbSegment: 'chart-of-accounts',
  },
  {
    id: 'account-edit',
    path: '/accounting/chart-of-accounts/:accountId/edit',
    title: 'Edit account',
    layout: 'app',
    showInNav: false,
    anyOf: ['account.view'],
    projectScope: 'none',
    breadcrumbSegment: 'chart-of-accounts',
  },
  {
    id: 'journals',
    path: '/accounting/journals',
    title: 'Journals',
    layout: 'app',
    showInNav: true,
    groupId: 'accounting',
    icon: 'finance',
    anyOf: ['journal.view'],
    projectScope: 'none',
    breadcrumbSegment: 'journals',
  },
  {
    id: 'journal-create',
    path: '/accounting/journals/new',
    title: 'New Journal',
    layout: 'app',
    showInNav: true,
    groupId: 'accounting',
    icon: 'finance',
    anyOf: ['journal.create'],
    projectScope: 'none',
    breadcrumbSegment: 'journals',
  },
  {
    id: 'journal-detail',
    path: '/accounting/journals/:journalId',
    title: 'Journal',
    layout: 'app',
    showInNav: false,
    anyOf: ['journal.view'],
    projectScope: 'none',
    breadcrumbSegment: 'journals',
  },
  {
    id: 'cash-accounts',
    path: '/accounting/cash-accounts',
    title: 'Cash & Petty Cash',
    layout: 'app',
    showInNav: true,
    groupId: 'accounting',
    icon: 'finance',
    anyOf: ['cash.view'],
    projectScope: 'required',
    breadcrumbSegment: 'cash-accounts',
  },
  {
    id: 'bank-accounts',
    path: '/accounting/bank-accounts',
    title: 'Bank Accounts',
    layout: 'app',
    showInNav: true,
    groupId: 'accounting',
    icon: 'finance',
    anyOf: ['bank.view'],
    projectScope: 'none',
    breadcrumbSegment: 'bank-accounts',
  },
  {
    id: 'bank-account-detail',
    path: '/accounting/bank-accounts/:bankAccountId',
    title: 'Bank Account',
    layout: 'app',
    showInNav: false,
    anyOf: ['bank.view'],
    projectScope: 'none',
    breadcrumbSegment: 'bank-accounts',
  },
  {
    id: 'bank-reconciliation',
    path: '/accounting/bank-reconciliation',
    title: 'Bank Reconciliation',
    layout: 'app',
    showInNav: true,
    groupId: 'accounting',
    icon: 'finance',
    anyOf: ['bank_reconciliation.view'],
    projectScope: 'none',
    breadcrumbSegment: 'bank-reconciliation',
  },
  {
    id: 'bank-reconciliation-detail',
    path: '/accounting/bank-reconciliation/:sessionId',
    title: 'Reconciliation Session',
    layout: 'app',
    showInNav: false,
    anyOf: ['bank_reconciliation.view'],
    projectScope: 'none',
    breadcrumbSegment: 'bank-reconciliation',
  },
  {
    id: 'financial-years',
    path: '/accounting/financial-years',
    title: 'Financial Years',
    layout: 'app',
    showInNav: true,
    groupId: 'accounting',
    icon: 'finance',
    anyOf: ['financial_year.view'],
    projectScope: 'none',
    breadcrumbSegment: 'financial-years',
  },
  {
    id: 'financial-year-create',
    path: '/accounting/financial-years/new',
    title: 'New Financial Year',
    layout: 'app',
    showInNav: false,
    anyOf: ['financial_year.manage'],
    projectScope: 'none',
    breadcrumbSegment: 'financial-years',
  },
  {
    id: 'financial-year-detail',
    path: '/accounting/financial-years/:financialYearId',
    title: 'Financial Year',
    layout: 'app',
    showInNav: false,
    anyOf: ['financial_year.view'],
    projectScope: 'none',
    breadcrumbSegment: 'financial-years',
  },
  {
    id: 'period-close',
    path: '/accounting/period-close',
    title: 'Period Closure',
    layout: 'app',
    showInNav: true,
    groupId: 'accounting',
    icon: 'finance',
    anyOf: ['period_closure.view'],
    projectScope: 'none',
    breadcrumbSegment: 'period-close',
  },
  {
    id: 'cost-centres',
    path: '/accounting/cost-centres',
    title: 'Cost Centres',
    layout: 'app',
    showInNav: true,
    groupId: 'accounting',
    icon: 'finance',
    anyOf: ['cost_centre.view'],
    projectScope: 'none',
    breadcrumbSegment: 'cost-centres',
  },
  {
    id: 'opening-balances',
    path: '/accounting/opening-balances',
    title: 'Opening Balances',
    layout: 'app',
    showInNav: true,
    groupId: 'accounting',
    icon: 'finance',
    anyOf: ['opening_balance.view'],
    projectScope: 'none',
    breadcrumbSegment: 'opening-balances',
  },
  {
    id: 'gst',
    path: '/accounting/gst',
    title: 'GST',
    layout: 'app',
    showInNav: true,
    groupId: 'accounting',
    icon: 'finance',
    anyOf: ['gst.view'],
    projectScope: 'none',
    breadcrumbSegment: 'gst',
  },
  {
    id: 'tds',
    path: '/accounting/tds',
    title: 'TDS',
    layout: 'app',
    showInNav: true,
    groupId: 'accounting',
    icon: 'finance',
    anyOf: ['tds.view'],
    projectScope: 'none',
    breadcrumbSegment: 'tds',
  },
  {
    id: 'budgets',
    path: '/accounting/budgets',
    title: 'Budgets',
    layout: 'app',
    showInNav: true,
    groupId: 'accounting',
    icon: 'finance',
    anyOf: ['budget.view'],
    projectScope: 'required',
    breadcrumbSegment: 'budgets',
  },
  {
    id: 'fixed-assets',
    path: '/accounting/fixed-assets',
    title: 'Fixed Assets',
    layout: 'app',
    showInNav: true,
    groupId: 'accounting',
    icon: 'finance',
    anyOf: ['fixed_asset.view'],
    projectScope: 'required',
    breadcrumbSegment: 'fixed-assets',
  },
  {
    id: 'customer-invoices',
    path: '/accounting/customer-invoices',
    title: 'Customer Invoices',
    layout: 'app',
    showInNav: true,
    groupId: 'accounting',
    icon: 'finance',
    anyOf: ['customer_invoice.view'],
    projectScope: 'required',
    breadcrumbSegment: 'customer-invoices',
  },
  {
    id: 'expense-categories',
    path: '/accounting/expense-categories',
    title: 'Expense Categories',
    layout: 'app',
    showInNav: true,
    groupId: 'petty-cash',
    icon: 'finance',
    anyOf: ['expense_category.view'],
    projectScope: 'none',
    breadcrumbSegment: 'expense-categories',
  },
  {
    id: 'site-expenses',
    path: '/accounting/expenses',
    title: 'Site Expenses',
    layout: 'app',
    showInNav: true,
    groupId: 'petty-cash',
    icon: 'finance',
    anyOf: ['expense.view'],
    projectScope: 'required',
    breadcrumbSegment: 'expenses',
  },
  {
    id: 'site-expense-detail',
    path: '/accounting/expenses/:expenseId',
    title: 'Expense Voucher',
    layout: 'app',
    showInNav: false,
    anyOf: ['expense.view'],
    projectScope: 'required',
    breadcrumbSegment: 'expenses',
  },
  {
    id: 'petty-cash-requests',
    path: '/accounting/petty-cash/requests',
    title: 'Fund Requests',
    layout: 'app',
    showInNav: true,
    groupId: 'petty-cash',
    icon: 'finance',
    anyOf: ['petty_cash.view'],
    projectScope: 'required',
    breadcrumbSegment: 'requests',
  },
  {
    id: 'petty-cash-request-create',
    path: '/accounting/petty-cash/requests/new',
    title: 'New Petty Cash Request',
    layout: 'app',
    showInNav: false,
    anyOf: ['petty_cash.request'],
    projectScope: 'required',
    breadcrumbSegment: 'requests',
  },
  {
    id: 'petty-cash-request-detail',
    path: '/accounting/petty-cash/requests/:requestId',
    title: 'Petty Cash Request',
    layout: 'app',
    showInNav: false,
    anyOf: ['petty_cash.view'],
    projectScope: 'required',
    breadcrumbSegment: 'requests',
  },
  {
    id: 'petty-cash-fund-transfers',
    path: '/accounting/petty-cash/transfers',
    title: 'Fund Transfers',
    layout: 'app',
    showInNav: true,
    groupId: 'petty-cash',
    icon: 'finance',
    anyOf: ['petty_cash.view'],
    projectScope: 'required',
    breadcrumbSegment: 'transfers',
  },
  {
    id: 'grns',
    path: '/inventory/grns',
    title: 'Goods Receipts',
    layout: 'app',
    showInNav: true,
    groupId: 'inventory',
    icon: 'stock',
    anyOf: ['grn.create'],
    projectScope: 'required',
    breadcrumbSegment: 'grns',
  },
  {
    id: 'grn-detail',
    path: '/inventory/grns/:grnId',
    title: 'Goods Receipt',
    layout: 'app',
    showInNav: false,
    anyOf: ['grn.create'],
    projectScope: 'required',
    breadcrumbSegment: 'grns',
  },
  {
    id: 'quality-inspections',
    path: '/inventory/quality-inspections',
    title: 'Quality Inspections',
    layout: 'app',
    showInNav: true,
    groupId: 'inventory',
    icon: 'stock',
    anyOf: ['quality.view'],
    projectScope: 'required',
    breadcrumbSegment: 'quality-inspections',
  },
  {
    id: 'quality-inspection-detail',
    path: '/inventory/quality-inspections/:inspectionId',
    title: 'Quality Inspection',
    layout: 'app',
    showInNav: false,
    anyOf: ['quality.view'],
    projectScope: 'required',
    breadcrumbSegment: 'quality-inspections',
  },
  {
    id: 'material-issues',
    path: '/inventory/material-issues',
    title: 'Material Issues',
    layout: 'app',
    showInNav: true,
    groupId: 'inventory',
    icon: 'stock',
    anyOf: ['stock.view'],
    projectScope: 'required',
    breadcrumbSegment: 'material-issues',
  },
  {
    id: 'material-issue-detail',
    path: '/inventory/material-issues/:issueId',
    title: 'Material Issue',
    layout: 'app',
    showInNav: false,
    anyOf: ['stock.view'],
    projectScope: 'required',
    breadcrumbSegment: 'material-issues',
  },
  {
    id: 'reorder-alerts',
    path: '/inventory/reorder-alerts',
    title: 'Reorder Alerts',
    layout: 'app',
    showInNav: true,
    groupId: 'inventory',
    icon: 'stock',
    anyOf: ['stock.view'],
    projectScope: 'required',
    breadcrumbSegment: 'reorder-alerts',
  },
  {
    id: 'boq-versions',
    path: '/project-control/boq/versions',
    title: 'BOQ Versions',
    layout: 'app',
    showInNav: true,
    groupId: 'project-control',
    icon: 'projects',
    anyOf: ['boq.view'],
    projectScope: 'required',
    breadcrumbSegment: 'versions',
  },
  {
    id: 'boq-item-editor',
    path: '/project-control/boq/items/:id',
    title: 'BOQ Item',
    layout: 'app',
    showInNav: false,
    anyOf: ['boq.view'],
    projectScope: 'required',
    breadcrumbSegment: 'items',
  },
  {
    id: 'construction-reports',
    path: '/reports/construction',
    title: 'Construction Reports',
    layout: 'app',
    showInNav: true,
    groupId: 'reports',
    icon: 'reports',
    anyOf: ['report.view'],
    projectScope: 'required',
    breadcrumbSegment: 'construction',
  },
  {
    id: 'accounting-reports',
    path: '/reports/accounting',
    title: 'Accounting Reports',
    layout: 'app',
    showInNav: true,
    groupId: 'reports',
    icon: 'reports',
    /** Company BS / P&L: select `balance-sheet` or `company-profit-and-loss` on this hub (`finance_statement.view`). */
    anyOf: ['report.view', 'finance_statement.view'],
    projectScope: 'none',
    breadcrumbSegment: 'accounting',
  },
  {
    id: 'cash-book',
    path: '/reports/accounting/cash-book',
    title: 'Cash Book',
    layout: 'app',
    showInNav: true,
    groupId: 'reports',
    icon: 'reports',
    anyOf: ['report.view'],
    projectScope: 'none',
    breadcrumbSegment: 'cash-book',
  },
  {
    id: 'bank-book',
    path: '/reports/accounting/bank-book',
    title: 'Bank Book',
    layout: 'app',
    showInNav: true,
    groupId: 'reports',
    icon: 'reports',
    anyOf: ['report.view'],
    projectScope: 'none',
    breadcrumbSegment: 'bank-book',
  },
  {
    id: 'users',
    path: '/users',
    title: 'Users',
    layout: 'app',
    showInNav: true,
    groupId: 'organisation',
    icon: 'users',
    anyOf: ['user.view'],
    projectScope: 'none',
  },
  {
    id: 'user-create',
    path: '/users/new',
    title: 'New User',
    layout: 'app',
    showInNav: false,
    anyOf: ['user.create'],
    projectScope: 'none',
    breadcrumbSegment: 'users',
  },
  {
    id: 'user-detail',
    path: '/users/:userId',
    title: 'User',
    layout: 'app',
    showInNav: false,
    anyOf: ['user.view'],
    projectScope: 'none',
    breadcrumbSegment: 'users',
  },
  {
    id: 'user-edit',
    path: '/users/:userId/edit',
    title: 'Edit User',
    layout: 'app',
    showInNav: false,
    allOf: ['user.view', 'user.update'],
    projectScope: 'none',
    breadcrumbSegment: 'users',
  },
  {
    id: 'company-overview',
    path: '/administration/company',
    title: 'Company',
    layout: 'app',
    showInNav: true,
    groupId: 'administration',
    icon: 'company',
    anyOf: ['company.view'],
    projectScope: 'none',
    breadcrumbSegment: 'company',
  },
  {
    id: 'company-settings',
    path: '/administration/company/settings',
    title: 'Company Settings',
    layout: 'app',
    showInNav: false,
    anyOf: ['company.view'],
    projectScope: 'none',
    breadcrumbSegment: 'company',
  },
  {
    id: 'employees',
    path: '/administration/employees',
    title: 'Employees',
    layout: 'app',
    showInNav: true,
    groupId: 'administration',
    icon: 'users',
    anyOf: ['employee.view'],
    projectScope: 'none',
    breadcrumbSegment: 'employees',
  },
  {
    id: 'employee-create',
    path: '/administration/employees/new',
    title: 'Create Employee',
    layout: 'app',
    showInNav: false,
    anyOf: ['employee.create'],
    projectScope: 'none',
    breadcrumbSegment: 'employees',
  },
  {
    id: 'employee-detail',
    path: '/administration/employees/:employeeId',
    title: 'Employee',
    layout: 'app',
    showInNav: false,
    anyOf: ['employee.view'],
    projectScope: 'none',
    breadcrumbSegment: 'employees',
  },
  {
    id: 'employee-access',
    path: '/administration/employees/:employeeId/access',
    title: 'Employee Access',
    layout: 'app',
    showInNav: false,
    anyOf: ['employee.view'],
    projectScope: 'none',
    breadcrumbSegment: 'employees',
  },
  {
    id: 'departments',
    path: '/administration/departments',
    title: 'Departments',
    layout: 'app',
    showInNav: true,
    groupId: 'administration',
    icon: 'company',
    anyOf: ['department.view'],
    projectScope: 'none',
    breadcrumbSegment: 'departments',
  },
  {
    id: 'designations',
    path: '/administration/designations',
    title: 'Designations',
    layout: 'app',
    showInNav: true,
    groupId: 'administration',
    icon: 'company',
    anyOf: ['designation.view'],
    projectScope: 'none',
    breadcrumbSegment: 'designations',
  },
  {
    id: 'site-access-admin',
    path: '/administration/site-access',
    title: 'Site Access',
    layout: 'app',
    showInNav: true,
    groupId: 'administration',
    icon: 'projects',
    anyOf: ['site_access.view'],
    projectScope: 'none',
    breadcrumbSegment: 'site-access',
  },
  {
    id: 'roles',
    path: '/administration/roles',
    title: 'Roles & Permissions',
    layout: 'app',
    showInNav: true,
    groupId: 'administration',
    icon: 'settings',
    anyOf: ['role.view'],
    projectScope: 'none',
    breadcrumbSegment: 'roles',
  },
  {
    id: 'role-create',
    path: '/administration/roles/new',
    title: 'New Role',
    layout: 'app',
    showInNav: false,
    anyOf: ['role.create'],
    projectScope: 'none',
    breadcrumbSegment: 'roles',
  },
  {
    id: 'role-detail',
    path: '/administration/roles/:roleId',
    title: 'Role',
    layout: 'app',
    showInNav: false,
    anyOf: ['role.view'],
    projectScope: 'none',
    breadcrumbSegment: 'roles',
  },
  {
    id: 'role-edit',
    path: '/administration/roles/:roleId/edit',
    title: 'Edit Role',
    layout: 'app',
    showInNav: false,
    allOf: ['role.view', 'role.update'],
    projectScope: 'none',
    breadcrumbSegment: 'roles',
  },
  {
    id: 'documents',
    path: '/documents',
    title: 'Documents',
    layout: 'app',
    showInNav: true,
    groupId: 'administration',
    icon: 'documents',
    anyOf: ['document.view'],
    projectScope: 'none',
  },
  {
    id: 'audit-logs',
    path: '/administration/audit-logs',
    title: 'Audit Logs',
    layout: 'app',
    showInNav: true,
    groupId: 'administration',
    icon: 'audit',
    anyOf: ['audit.view'],
    projectScope: 'none',
    breadcrumbSegment: 'audit-logs',
  },
  {
    id: 'director-digest',
    path: '/administration/director-digest',
    title: 'Director Digest',
    layout: 'app',
    showInNav: true,
    groupId: 'administration',
    icon: 'audit',
    anyOf: ['director_digest.view', 'director_digest.send'],
    projectScope: 'none',
    breadcrumbSegment: 'director-digest',
  },
  {
    id: 'approval-workflows',
    path: '/administration/approval-workflows',
    title: 'Approval Workflows',
    layout: 'app',
    showInNav: true,
    groupId: 'administration',
    icon: 'approvals',
    anyOf: ['approval.configure'],
    projectScope: 'none',
    breadcrumbSegment: 'approval-workflows',
  },
  {
    id: 'system-health',
    path: '/administration/system-health',
    title: 'System Health',
    layout: 'app',
    showInNav: true,
    groupId: 'administration',
    icon: 'audit',
    anyOf: ['audit.view'],
    projectScope: 'none',
    breadcrumbSegment: 'system-health',
  },
  {
    id: 'settings',
    path: '/settings',
    title: 'Settings',
    layout: 'app',
    showInNav: true,
    groupId: 'system',
    icon: 'settings',
    projectScope: 'none',
  },
  {
    id: 'forbidden',
    path: '/forbidden',
    title: 'Access denied',
    layout: 'app',
    showInNav: false,
    projectScope: 'none',
  },
  {
    id: 'no-project-access',
    path: '/no-project-access',
    title: 'No project access',
    layout: 'app',
    showInNav: false,
    projectScope: 'none',
  },
  {
    id: 'dev-data-table',
    path: '/dev/data-table',
    title: 'DataTable demo',
    layout: 'app',
    showInNav: false,
    projectScope: 'none',
  },
  {
    id: 'dev-forms',
    path: '/dev/forms',
    title: 'Forms demo',
    layout: 'app',
    showInNav: false,
    projectScope: 'none',
  },
  {
    id: 'dev-documents',
    path: '/dev/documents',
    title: 'Documents demo',
    layout: 'app',
    showInNav: false,
    projectScope: 'none',
  },
  {
    id: 'dev-workflow-timeline',
    path: '/dev/workflow-timeline',
    title: 'Workflow timeline demo',
    layout: 'app',
    showInNav: false,
    projectScope: 'none',
  },
  {
    id: 'dev-entity-detail',
    path: '/dev/entity-detail',
    title: 'Entity detail demo',
    layout: 'app',
    showInNav: false,
    projectScope: 'none',
  },
  {
    id: 'dev-print-pdf',
    path: '/dev/print-pdf',
    title: 'Print / PDF demo',
    layout: 'app',
    showInNav: false,
    projectScope: 'none',
  },
  {
    id: 'dev-export',
    path: '/dev/export',
    title: 'Export demo',
    layout: 'app',
    showInNav: false,
    projectScope: 'none',
  },
] as const satisfies readonly AppRouteDefinition[];

export const APP_ROUTE_REGISTRY: readonly AppRouteDefinition[] =
  defineRouteRegistry(APP_ROUTES);

export type AppRouteId = (typeof APP_ROUTES)[number]['id'];

export type NavItemConfig = {
  id: string;
  label: string;
  to: string;
  anyOf?: readonly PermissionCode[];
  allOf?: readonly PermissionCode[];
  end?: boolean;
  icon: NavIconId;
  projectScope: ProjectScopeMode;
};

export type NavGroupConfig = {
  id: NavGroupId;
  label: string;
  items: readonly NavItemConfig[];
};

function toNavItem(route: AppRouteDefinition): NavItemConfig {
  if (!route.icon) {
    throw new Error(`Nav route ${route.id} is missing icon`);
  }
  return {
    id: route.id,
    label: route.title,
    to: route.path,
    anyOf: route.anyOf,
    allOf: route.allOf,
    end: route.end,
    icon: route.icon,
    projectScope: route.projectScope,
  };
}

/** Sidebar groups derived from the registry (permission filter applied later). */
export function buildNavGroupsFromRegistry(
  routes: readonly AppRouteDefinition[] = APP_ROUTE_REGISTRY,
): NavGroupConfig[] {
  return NAV_GROUP_META.map((group) => ({
    id: group.id,
    label: group.label,
    items: routes
      .filter(
        (route) =>
          route.layout === 'app' &&
          route.showInNav &&
          route.groupId === group.id,
      )
      .map(toNavItem),
  })).filter((group) => group.items.length > 0);
}

export const NAV_GROUPS = buildNavGroupsFromRegistry();

export function getRouteById(
  id: string,
): AppRouteDefinition | undefined {
  return APP_ROUTE_REGISTRY.find((route) => route.id === id);
}

export function requireRouteById(id: AppRouteId): AppRouteDefinition {
  const route = getRouteById(id);
  if (!route) {
    throw new Error(`Unknown route id: ${id}`);
  }
  return route;
}

/** Normalise pathname for matching (`/projects/` → `/projects`). */
export function normalisePathname(pathname: string): string {
  if (pathname.length > 1 && pathname.endsWith('/')) {
    return pathname.slice(0, -1);
  }
  return pathname || '/';
}

/** Match `/projects/:projectId/dashboard` style registry paths. */
export function pathMatchesPattern(
  pattern: string,
  pathname: string,
): boolean {
  const patternParts = pattern.split('/').filter(Boolean);
  const pathParts = pathname.split('/').filter(Boolean);
  if (patternParts.length !== pathParts.length) {
    return false;
  }
  return patternParts.every(
    (part, index) => part.startsWith(':') || part === pathParts[index],
  );
}

export function findRouteByPathname(
  pathname: string,
): AppRouteDefinition | undefined {
  const normalised = normalisePathname(pathname);

  const exact = APP_ROUTE_REGISTRY.find((route) => route.path === normalised);
  if (exact) {
    return exact;
  }

  const paramMatch = APP_ROUTE_REGISTRY.filter((route) =>
    route.path.includes(':')
      ? pathMatchesPattern(route.path, normalised)
      : false,
  ).sort((a, b) => b.path.length - a.path.length)[0];
  if (paramMatch) {
    return paramMatch;
  }

  // Longest prefix match for nested future routes (skip param patterns)
  const candidates = APP_ROUTE_REGISTRY.filter(
    (route) =>
      route.path !== '/' &&
      !route.end &&
      !route.path.includes(':') &&
      (normalised === route.path || normalised.startsWith(`${route.path}/`)),
  ).sort((a, b) => b.path.length - a.path.length);

  return candidates[0];
}

/** React Router path relative to AppLayout (no leading slash). */
export function toRelativeAppPath(absolutePath: string): string {
  if (absolutePath === '/') {
    return '';
  }
  return absolutePath.replace(/^\//, '');
}

export const ROUTE_LABELS: Record<string, string> = {
  ...Object.fromEntries(
    APP_ROUTE_REGISTRY.flatMap((route) => {
      const entries: Array<[string, string]> = [];
      if (route.path === '/') {
        entries.push(['', route.title]);
      } else {
        const segments = route.path.split('/').filter(Boolean);
        const last = segments[segments.length - 1];
        if (last) {
          entries.push([last, route.title]);
        }
        if (route.breadcrumbSegment) {
          entries.push([route.breadcrumbSegment, route.title]);
        }
      }
      return entries;
    }),
  ),
  /** Parent crumb for `/dashboard/director`. */
  dashboard: 'Dashboard',
  /** Parent crumb for `/projects/*` project-management routes. */
  projects: 'Projects',
  users: 'Users',
  /** Parent crumb for `/administration/audit-logs`. */
  administration: 'Administration',
  company: 'Company',
  roles: 'Roles & Permissions',
  /** Parent crumb for `/capital/*`. */
  capital: 'Capital & Investment',
  /** Parent crumb for `/accounting/*`. */
  accounting: 'Accounting',
  'financial-years': 'Financial Years',
  /** Parent crumb for `/accounting/petty-cash/*`. */
  'petty-cash': 'Petty Cash',
  /** Parent crumb for `/inventory/*`. */
  inventory: 'Inventory',
  /** Parent crumb for `/project-control/*`. */
  'project-control': 'Project Control',
  boq: 'BOQ',
};

export function getRouteLabel(segment: string): string {
  return ROUTE_LABELS[segment] ?? segment;
}

export function getPageTitle(pathname: string): string {
  const route = findRouteByPathname(pathname);
  if (route) {
    return route.title;
  }
  const parts = normalisePathname(pathname).split('/').filter(Boolean);
  if (parts.length === 0) {
    return 'Dashboard';
  }
  return getRouteLabel(parts[parts.length - 1] ?? '');
}
