import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import type { DailyProgressReport } from './schemas/daily-progress-report.schema';

@Injectable()
export class DprPdfService {
  async buildPdfBuffer(dpr: DailyProgressReport): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 48, size: 'A4' });
      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      doc.fontSize(16).text('Luxaria Developers Pvt. Ltd.', { align: 'center' });
      doc.moveDown(0.3);
      doc.fontSize(13).text('Daily Progress Report', { align: 'center' });
      doc.moveDown();
      doc.fontSize(10);
      doc.text(`DPR No: ${dpr.dprNumber}`);
      doc.text(`Date: ${dpr.reportDate.toISOString().slice(0, 10)}`);
      doc.text(`Status: ${dpr.status}`);
      doc.text(`Weather: ${dpr.weather}${dpr.weatherNotes ? ` — ${dpr.weatherNotes}` : ''}`);
      doc.text(
        `Labour: ${dpr.labourCount} (skilled ${dpr.skilledLabourCount}, unskilled ${dpr.unskilledLabourCount})`,
      );
      doc.text(
        `Site cash balance: INR ${Number(dpr.siteCashBalance).toLocaleString('en-IN')}`,
      );
      doc.moveDown(0.5);

      doc.fontSize(11).text('Work performed', { underline: true });
      doc.fontSize(10).text(dpr.workPerformed || '—');
      doc.moveDown(0.5);

      if (dpr.staffPresent?.length) {
        doc.fontSize(11).text('Staff present', { underline: true });
        doc.fontSize(10);
        for (const s of dpr.staffPresent) {
          doc.text(
            `• ${s.name}${s.role ? ` (${s.role})` : ''}${s.present === false ? ' — absent' : ''}`,
          );
        }
        doc.moveDown(0.4);
      }

      if (dpr.boqQuantities?.length) {
        doc.fontSize(11).text('BOQ quantities completed', { underline: true });
        doc.fontSize(10);
        for (const b of dpr.boqQuantities) {
          doc.text(
            `• ${b.boqCode ?? String(b.boqItemId)}: ${b.quantityCompleted} ${b.unit ?? ''}`.trim(),
          );
        }
        doc.moveDown(0.4);
      }

      if (dpr.materialsReceived?.length) {
        doc.fontSize(11).text('Materials received', { underline: true });
        doc.fontSize(10);
        for (const m of dpr.materialsReceived) {
          doc.text(`• ${m.materialName}: ${m.quantity} ${m.unit ?? ''}`.trim());
        }
        doc.moveDown(0.4);
      }

      if (dpr.materialsIssued?.length) {
        doc.fontSize(11).text('Materials issued', { underline: true });
        doc.fontSize(10);
        for (const m of dpr.materialsIssued) {
          doc.text(`• ${m.materialName}: ${m.quantity} ${m.unit ?? ''}`.trim());
        }
        doc.moveDown(0.4);
      }

      if (dpr.equipmentUsed?.length) {
        doc.fontSize(11).text('Equipment used', { underline: true });
        doc.fontSize(10);
        for (const e of dpr.equipmentUsed) {
          doc.text(`• ${e.name}: ${e.hours} hrs`);
        }
        doc.moveDown(0.4);
      }

      if (dpr.delays?.length) {
        doc.fontSize(11).text('Delays', { underline: true });
        doc.fontSize(10);
        for (const d of dpr.delays) {
          doc.text(`• ${d.reason} (${d.hoursLost} hrs)`);
        }
        doc.moveDown(0.4);
      }

      if (dpr.safetyIssues?.length) {
        doc.fontSize(11).text('Safety issues', { underline: true });
        doc.fontSize(10);
        for (const i of dpr.safetyIssues) {
          doc.text(`• [${i.severity}] ${i.description}`);
        }
        doc.moveDown(0.4);
      }

      if (dpr.qualityIssues?.length) {
        doc.fontSize(11).text('Quality issues', { underline: true });
        doc.fontSize(10);
        for (const i of dpr.qualityIssues) {
          doc.text(`• [${i.severity}] ${i.description}`);
        }
        doc.moveDown(0.4);
      }

      if (dpr.decisionsRequired?.length) {
        doc.fontSize(11).text('Decisions required', { underline: true });
        doc.fontSize(10);
        for (const d of dpr.decisionsRequired) {
          doc.text(`• ${d.description}${d.owner ? ` — ${d.owner}` : ''}`);
        }
        doc.moveDown(0.4);
      }

      doc.fontSize(11).text('Tomorrow plan', { underline: true });
      doc.fontSize(10).text(dpr.tomorrowPlan || '—');
      doc.moveDown();
      doc
        .fontSize(9)
        .fillColor('#555555')
        .text(
          `Photos: ${dpr.photoDocumentIds?.length ?? 0} · Videos: ${dpr.videoDocumentIds?.length ?? 0}`,
        );
      doc.text('Generated by Luxaria Developers ERP. PDF is created on submit.');
      doc.end();
    });
  }
}
