import {
  AccountCategory,
  AccountType,
} from './schemas/account.schema';

export type AccountSeedDefinition = {
  accountCode: string;
  accountName: string;
  accountType: AccountType;
  accountCategory: AccountCategory;
  parentCode: string | null;
  isControlAccount: boolean;
  allowManualPosting: boolean;
  requiresProject: boolean;
  requiresParty: boolean;
};

/**
 * Standard construction chart of accounts for Luxaria Developers.
 * Codes are stable; seed is idempotent by accountCode.
 */
export const STANDARD_CONSTRUCTION_COA: AccountSeedDefinition[] = [
  // ── Assets ─────────────────────────────────────────────────────────────
  {
    accountCode: '1000',
    accountName: 'Assets',
    accountType: AccountType.Asset,
    accountCategory: AccountCategory.Control,
    parentCode: null,
    isControlAccount: true,
    allowManualPosting: false,
    requiresProject: false,
    requiresParty: false,
  },
  {
    accountCode: '1100',
    accountName: 'Current Assets',
    accountType: AccountType.Asset,
    accountCategory: AccountCategory.Control,
    parentCode: '1000',
    isControlAccount: true,
    allowManualPosting: false,
    requiresProject: false,
    requiresParty: false,
  },
  {
    accountCode: '1110',
    accountName: 'Bank Accounts',
    accountType: AccountType.Asset,
    accountCategory: AccountCategory.Bank,
    parentCode: '1100',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: false,
    requiresParty: false,
  },
  {
    accountCode: '1120',
    accountName: 'Cash',
    accountType: AccountType.Asset,
    accountCategory: AccountCategory.Cash,
    parentCode: '1100',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: false,
    requiresParty: false,
  },
  {
    accountCode: '1130',
    accountName: 'Petty Cash',
    accountType: AccountType.Asset,
    accountCategory: AccountCategory.PettyCash,
    parentCode: '1100',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: false,
    requiresParty: false,
  },
  {
    accountCode: '1140',
    accountName: 'Input GST',
    accountType: AccountType.Asset,
    accountCategory: AccountCategory.InputGst,
    parentCode: '1100',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: false,
    requiresParty: false,
  },
  {
    accountCode: '1150',
    accountName: 'Work in Progress',
    accountType: AccountType.Asset,
    accountCategory: AccountCategory.WorkInProgress,
    parentCode: '1100',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: true,
    requiresParty: false,
  },
  {
    accountCode: '1160',
    accountName: 'Contractor Advance',
    accountType: AccountType.Asset,
    accountCategory: AccountCategory.ContractorAdvance,
    parentCode: '1100',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: true,
    requiresParty: true,
  },
  {
    accountCode: '1200',
    accountName: 'Non-Current Assets',
    accountType: AccountType.Asset,
    accountCategory: AccountCategory.Control,
    parentCode: '1000',
    isControlAccount: true,
    allowManualPosting: false,
    requiresProject: false,
    requiresParty: false,
  },
  {
    accountCode: '1210',
    accountName: 'Land Cost',
    accountType: AccountType.Asset,
    accountCategory: AccountCategory.LandCost,
    parentCode: '1200',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: true,
    requiresParty: false,
  },
  {
    accountCode: '1211',
    accountName: 'Land registration & stamp duty',
    accountType: AccountType.Asset,
    accountCategory: AccountCategory.LandCost,
    parentCode: '1210',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: true,
    requiresParty: false,
  },

  // ── Liabilities ────────────────────────────────────────────────────────
  {
    accountCode: '2000',
    accountName: 'Liabilities',
    accountType: AccountType.Liability,
    accountCategory: AccountCategory.Control,
    parentCode: null,
    isControlAccount: true,
    allowManualPosting: false,
    requiresProject: false,
    requiresParty: false,
  },
  {
    accountCode: '2100',
    accountName: 'Current Liabilities',
    accountType: AccountType.Liability,
    accountCategory: AccountCategory.Control,
    parentCode: '2000',
    isControlAccount: true,
    allowManualPosting: false,
    requiresProject: false,
    requiresParty: false,
  },
  {
    accountCode: '2110',
    accountName: 'Vendor Payable',
    accountType: AccountType.Liability,
    accountCategory: AccountCategory.VendorPayable,
    parentCode: '2100',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: true,
    requiresParty: true,
  },
  {
    accountCode: '2120',
    accountName: 'Contractor Payable',
    accountType: AccountType.Liability,
    accountCategory: AccountCategory.ContractorPayable,
    parentCode: '2100',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: true,
    requiresParty: true,
  },
  {
    accountCode: '2130',
    accountName: 'Labour Payable',
    accountType: AccountType.Liability,
    accountCategory: AccountCategory.LabourPayable,
    parentCode: '2100',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: true,
    requiresParty: true,
  },
  {
    accountCode: '2140',
    accountName: 'Customer Advance',
    accountType: AccountType.Liability,
    accountCategory: AccountCategory.CustomerAdvance,
    parentCode: '2100',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: true,
    requiresParty: true,
  },
  {
    accountCode: '2150',
    accountName: 'Output GST',
    accountType: AccountType.Liability,
    accountCategory: AccountCategory.OutputGst,
    parentCode: '2100',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: false,
    requiresParty: false,
  },
  {
    accountCode: '2160',
    accountName: 'TDS Payable',
    accountType: AccountType.Liability,
    accountCategory: AccountCategory.TdsPayable,
    parentCode: '2100',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: false,
    requiresParty: false,
  },
  {
    accountCode: '2170',
    accountName: 'Retention Payable',
    accountType: AccountType.Liability,
    accountCategory: AccountCategory.RetentionPayable,
    parentCode: '2100',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: true,
    requiresParty: true,
  },
  {
    accountCode: '2200',
    accountName: 'Loans',
    accountType: AccountType.Liability,
    accountCategory: AccountCategory.Control,
    parentCode: '2000',
    isControlAccount: true,
    allowManualPosting: false,
    requiresProject: false,
    requiresParty: false,
  },
  {
    accountCode: '2210',
    accountName: 'Loan',
    accountType: AccountType.Liability,
    accountCategory: AccountCategory.Loan,
    parentCode: '2200',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: false,
    requiresParty: true,
  },

  // ── Equity ─────────────────────────────────────────────────────────────
  {
    accountCode: '3000',
    accountName: 'Equity',
    accountType: AccountType.Equity,
    accountCategory: AccountCategory.Control,
    parentCode: null,
    isControlAccount: true,
    allowManualPosting: false,
    requiresProject: false,
    requiresParty: false,
  },
  {
    accountCode: '3100',
    accountName: 'Director Account',
    accountType: AccountType.Equity,
    accountCategory: AccountCategory.DirectorAccount,
    parentCode: '3000',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: false,
    requiresParty: true,
  },
  {
    accountCode: '3200',
    accountName: 'Investor Account',
    accountType: AccountType.Equity,
    accountCategory: AccountCategory.InvestorAccount,
    parentCode: '3000',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: true,
    requiresParty: true,
  },

  // ── Income ─────────────────────────────────────────────────────────────
  {
    accountCode: '4000',
    accountName: 'Income',
    accountType: AccountType.Income,
    accountCategory: AccountCategory.Control,
    parentCode: null,
    isControlAccount: true,
    allowManualPosting: false,
    requiresProject: false,
    requiresParty: false,
  },
  {
    accountCode: '4100',
    accountName: 'Sales',
    accountType: AccountType.Income,
    accountCategory: AccountCategory.Sales,
    parentCode: '4000',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: true,
    requiresParty: true,
  },
  {
    accountCode: '4200',
    accountName: 'Other Income',
    accountType: AccountType.Income,
    accountCategory: AccountCategory.OtherIncome,
    parentCode: '4000',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: false,
    requiresParty: false,
  },
  {
    accountCode: '4210',
    accountName: 'Material Recovery',
    accountType: AccountType.Income,
    accountCategory: AccountCategory.MaterialRecovery,
    parentCode: '4000',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: true,
    requiresParty: true,
  },
  {
    accountCode: '4220',
    accountName: 'Penalty Recovery',
    accountType: AccountType.Income,
    accountCategory: AccountCategory.PenaltyRecovery,
    parentCode: '4000',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: true,
    requiresParty: true,
  },
  {
    accountCode: '4230',
    accountName: 'Other Contractor Deduction',
    accountType: AccountType.Income,
    accountCategory: AccountCategory.OtherContractorDeduction,
    parentCode: '4000',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: true,
    requiresParty: false,
  },
  {
    accountCode: '4300',
    accountName: 'Interest Income',
    accountType: AccountType.Income,
    accountCategory: AccountCategory.Interest,
    parentCode: '4000',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: false,
    requiresParty: false,
  },

  // ── Expenses ───────────────────────────────────────────────────────────
  {
    accountCode: '5000',
    accountName: 'Expenses',
    accountType: AccountType.Expense,
    accountCategory: AccountCategory.Control,
    parentCode: null,
    isControlAccount: true,
    allowManualPosting: false,
    requiresProject: false,
    requiresParty: false,
  },
  {
    accountCode: '5100',
    accountName: 'Direct Expense',
    accountType: AccountType.Expense,
    accountCategory: AccountCategory.DirectExpense,
    parentCode: '5000',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: true,
    requiresParty: false,
  },
  {
    accountCode: '5200',
    accountName: 'Indirect Expense',
    accountType: AccountType.Expense,
    accountCategory: AccountCategory.IndirectExpense,
    parentCode: '5000',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: false,
    requiresParty: false,
  },
  {
    accountCode: '5300',
    accountName: 'Material Purchase',
    accountType: AccountType.Expense,
    accountCategory: AccountCategory.MaterialPurchase,
    parentCode: '5000',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: true,
    requiresParty: true,
  },
  {
    accountCode: '5400',
    accountName: 'Interest Expense',
    accountType: AccountType.Expense,
    accountCategory: AccountCategory.Interest,
    parentCode: '5000',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: false,
    requiresParty: false,
  },
  {
    accountCode: '5110',
    accountName: 'Project approval / planning fee',
    accountType: AccountType.Expense,
    accountCategory: AccountCategory.DirectExpense,
    parentCode: '5000',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: true,
    requiresParty: false,
  },
  {
    accountCode: '5115',
    accountName: 'Government / statutory fee',
    accountType: AccountType.Expense,
    accountCategory: AccountCategory.DirectExpense,
    parentCode: '5000',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: true,
    requiresParty: false,
  },
  {
    accountCode: '5210',
    accountName: 'Site / office rent',
    accountType: AccountType.Expense,
    accountCategory: AccountCategory.IndirectExpense,
    parentCode: '5000',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: false,
    requiresParty: false,
  },
  {
    accountCode: '5220',
    accountName: 'Auditor fee',
    accountType: AccountType.Expense,
    accountCategory: AccountCategory.IndirectExpense,
    parentCode: '5000',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: false,
    requiresParty: false,
  },
  {
    accountCode: '5225',
    accountName: 'Company secretary fee',
    accountType: AccountType.Expense,
    accountCategory: AccountCategory.IndirectExpense,
    parentCode: '5000',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: false,
    requiresParty: false,
  },
  {
    accountCode: '5230',
    accountName: 'Advocate / legal fee',
    accountType: AccountType.Expense,
    accountCategory: AccountCategory.IndirectExpense,
    parentCode: '5000',
    isControlAccount: false,
    allowManualPosting: true,
    requiresProject: false,
    requiresParty: false,
  },
];
